// Generated by veil build — do not edit.

/** A managed secret. Deliberately registers no dependents: it is internal to whoever provisions it, and must never be inherited by a consumer. */
export interface SecretSpec {
  rotationDays: number;
  /** If set, the hook writes this instead — which the source schema rejects, since it demands an integer. Exists so the suite can prove setContent enforces the schema. */
  rotationLabel?: string;
}

export interface RegistryVariables {
  /** Which Acme environment is being rendered */
  environment: "staging" | "production";
  /** Cloud region every resource lands in */
  region: string;
}

export interface YamlCodec {
  /** Parse a YAML string into a JS value. Throws on malformed YAML. */
  parse(s: string): unknown;
  /** Serialize a JS value to YAML. Output uses 2-space indent and
   *  alphabetized keys (the gopkg.in/yaml.v3 default for maps). */
  stringify(value: unknown): string;
}

export interface Std {
  /** Read the entire file as a string, or null on failure. The path is
   *  resolved relative to the veil project root — the first ancestor
   *  directory (walking up from where `veil` was invoked) that
   *  contains a veil.json. */
  loadFile(path: string): string | null;
  /** Read the value of an environment variable, or undefined if unset. */
  getenv(name: string): string | undefined;
  /** YAML codec — parse and stringify without an npm dependency. Backed
   *  by gopkg.in/yaml.v3 on the host side. JSON is available via the
   *  native JSON global. */
  yaml: YamlCodec;
}

/** File metadata returned by os.stat / os.lstat. All values are numbers. */
export interface Stats {
  dev: number;
  ino: number;
  mode: number;
  nlink: number;
  uid: number;
  gid: number;
  rdev: number;
  size: number;
  blocks: number;
  atime: number;
  mtime: number;
  ctime: number;
}

export interface Os {
  /** List directory entries. Returns [names, error] — error is 0 on success. */
  readdir(path: string): [string[], number];
  /** File metadata, following symlinks. Returns [stats, error]. */
  stat(path: string): [Stats, number];
  /** File metadata, *not* following symlinks. Returns [stats, error]. */
  lstat(path: string): [Stats, number];
  /** Resolve to a canonical absolute path. Returns [path, error]. */
  realpath(path: string): [string, number];
  /** Read a symbolic link's target. Returns [target, error]. */
  readlink(path: string): [string, number];
  /** Process working directory — returns [cwd, error]. */
  getcwd(): [string, number];
  /** Platform identifier (e.g. "linux", "darwin"). */
  platform: string;
}

export interface FetchInit {
  method?: string;
  headers?: Record<string, string>;
  body?: string;
}

export interface FetchHeaders {
  get(name: string): string | null;
  has(name: string): boolean;
  forEach(fn: (value: string, key: string) => void): void;
}

export interface FetchResponse {
  status: number;
  statusText: string;
  ok: boolean;
  url: string;
  headers: FetchHeaders;
  text(): Promise<string>;
  json(): Promise<unknown>;
}

/** Web Fetch-style client. Strings only for body; no streaming, no
 *  AbortController. See SPEC.md for the full list of intentional gaps. */
export type Fetch = (
  input: string | (FetchInit & { url: string }),
  init?: FetchInit,
) => Promise<FetchResponse>;

export interface File<T = string> {
  /** Current contents. For a schema-declared source, validated against
   *  the schema on every call — a violation throws. The typed accessor
   *  hands back the parsed object; the plain File / escape hatch hands
   *  back the raw string (still validated underneath). */
  getContent(): T;
  /** Overwrite the contents. Same split and validation as getContent. */
  setContent(content: T): void;
  /** Current destination path, relative to the render output directory. */
  getPath(): string;
  /** Override the destination path. Identity (the FS key) is unchanged, so
   *  downstream hooks still find this file via the same typed accessor.
   *  Routing a file somewhere is a statement that it should be written, so
   *  this also marks it rendered. */
  setOutputPath(path: string): void;
  /** True when this file becomes rendered output. False for an asset the
   *  kind ships purely for hooks to read, and for anything deleted. */
  isRendered(): boolean;
  /** Turn output on or off for this entry. Turning it on clears the
   *  tombstone — a file cannot be both deleted and written. */
  setRendered(render: boolean): void;
  /** True when this file has been tombstoned via setDeleted(true) or
   *  fs.delete(). Downstream hooks still observe the entry; the final
   *  writer skips it. */
  isDeleted(): boolean;
  /** Tombstone (true) or restore (false) this entry. Identity is
   *  preserved either way — downstream hooks still find it via the same
   *  typed accessor. Tombstoning also stops the file rendering. */
  setDeleted(deleted: boolean): void;
}

export interface FS {
  /** Handle for the declared source "./sources/secret.json". */
  getSourcesSecretJson(): File<Secret>;

  /** Look up a file handle by its path. Returns undefined if absent.
   *  Always File<string> — still schema-enforced, just doesn't parse
   *  for you. */
  get(path: string): File | undefined;
  /** Every file handle currently present (including tombstoned ones —
   *  filter via `file.isDeleted()` if you only want live files). */
  getAll(): File[];
  /** Create a new file at the given path. Errors if a file with that path already exists. */
  add(path: string, content: string): File;
  /** Tombstone the file at the given path (soft delete — downstream hooks still see it). */
  delete(path: string): void;
  /** All paths currently present. */
  keys(): string[];
}

export interface Secret {
  rotationDays: number;
}

/** No targets accept this kind as a consumer; `dependencies` may only be omitted or empty. */
export type Dependency = never;

export interface Override {
  /** Path of the source file in the kind being replaced. */
  source: string;
  /** Local path to the override file. */
  path: string;
}

export interface Metadata {
  /** Name of the kind this resource instantiates. */
  kind: string;
  /** Name of this resource. */
  name: string;
  /** Source files ejected for local override. */
  overrides?: Override[];
}

export interface Resource<Spec, Deps = never> {
  /** Standard metadata common to every resource. */
  metadata: Metadata;
  /** Resource-specific data, validated against the kind's schema and
   *  with any matching overlays already merged in. */
  spec: Spec;
  /** Declared dependencies on other resources. The Deps type
   *  parameter narrows the per-entry shape to the targets this kind
   *  is actually allowed to depend on. */
  dependencies?: Deps[];
}

export interface RenderHookContext {
  /** The resource being rendered — full metadata + merged spec. */
  resource: Resource<SecretSpec, Dependency>;
  /** Path of the resource file being rendered, relative to the veil
   *  project root. Useful for hooks that need to locate sibling files
   *  (e.g. a service's package.json) by deriving paths from where the
   *  resource lives on disk. */
  path: string;
  /** Resolved input variables (from --var, env, or defaults). */
  vars: RegistryVariables;
  /** Absolute path of the veil project root — the directory housing
   *  veil.json. Provided for display / logging; std and os already
   *  resolve paths relative to this root. */
  root: string;
  /** Read-only file / env access. Paths resolve relative to the project
   *  root; use plain relative strings like "data.txt". */
  std: Std;
  /** Read-only filesystem inspection — list directories, stat, resolve
   *  symlinks. Paths resolve relative to the project root. */
  os: Os;
  /** Web Fetch-style HTTP client. Honors the host's allowlist, timeout,
   *  and response-size cap. */
  fetch: Fetch;
  /** Environment variables granted to this hook via its kind.json
   *  access.env declaration. Frozen — only the keys declared (and
   *  present on the host at render time) appear here. */
  env: Readonly<Record<string, string>>;
}

export interface RenderHook {
  /**
   * Called during `veil render` to transform the filesystem state for one
   * resource. Receives a RenderHookContext (resource, vars, root, std, os,
   * fetch) and the current FS; return the (optionally mutated) FS to flow
   * it into the next hook in the pipeline.
   *
   * Read declared sources via typed accessors (e.g. `fs.getSourcesDeploymentYaml()`)
   * — for a schema-declared source, getContent()/setContent() traffic in
   * the parsed, schema-validated object directly rather than a raw string.
   * Modify a file with `setContent`, `setOutputPath`, or `setDeleted`. Create
   * new files with `fs.add(path, content)`. Soft-delete with `fs.delete(path)` —
   * tombstoned files persist so downstream hooks can observe them via
   * `file.isDeleted()`, and are skipped at final write. A kind can also
   * ship assets: files declared without `render`, readable here and never
   * written, which `setRendered(true)` promotes to output.
   *
   * Returning nothing passes the FS through unchanged. `throw new Error(...)`
   * to abort the render for this resource. May be `async` — the host awaits
   * the returned Promise transparently before handing the result off.
   */
  render(ctx: RenderHookContext, fs: FS): FS | void | Promise<FS | void>;
}

export interface ValidationIssue {
  /** Required. Human-readable description of what failed. Surfaced
   *  verbatim in the aggregated render report. */
  message: string;
  /** Optional FS path or JSON-pointer-style locator that pinpoints where
   *  the issue lives (e.g. `sources/app.yaml` or `spec.replicas`). */
  path?: string;
  /** Optional severity tag. `'error'` (the default) fails the render;
   *  `'warning'` is reported but does not fail. */
  severity?: 'error' | 'warning';
}

/** A validate hook may return an issue list, a single issue, a single
 *  message string, or nothing. Throwing is treated as a single
 *  error-severity issue. */
export type ValidationResult =
  | void
  | string
  | ValidationIssue
  | Array<string | ValidationIssue>;

export interface ValidateHook {
  /**
   * Called during `veil render` after every other lifecycle point has
   * finished (kind render hooks, dependents, and any resource-level
   * hooks). Receives the same RenderHookContext + FS as a render hook
   * but is purely observational: any mutations the hook makes to the
   * FS or ctx are discarded by the runner. Returning a list of
   * issues — or throwing — fails the render with an aggregated
   * report. Every validate hook on the kind runs regardless of
   * failures so authors see every issue at once. May be `async`.
   */
  validate(ctx: RenderHookContext, fs: FS): ValidationResult | Promise<ValidationResult>;
}

// ---- Dependent hook types ----------------------------------------------
// One block per consumer kind that may declare a dependency on this
// kind. Each block replicates the consumer's spec / FS shape so the
// per-consumer hook receives concretely-typed `consumer` and `fs`.

/** A managed Postgres instance. */
export interface PostgresSpec {
  multiAz: boolean;
  size: "small" | "medium" | "large";
  storageGb: number;
}

export interface PostgresFS {
  /** Handle for the declared source "./sources/database.json". */
  getSourcesDatabaseJson(): File<PostgresDatabase>;

  /** Look up a file handle by its path. Returns undefined if absent.
   *  Always File<string> — still schema-enforced, just doesn't parse
   *  for you. */
  get(path: string): File | undefined;
  /** Every file handle currently present (including tombstoned ones —
   *  filter via `file.isDeleted()` if you only want live files). */
  getAll(): File[];
  /** Create a new file at the given path. Errors if a file with that path already exists. */
  add(path: string, content: string): File;
  /** Tombstone the file at the given path (soft delete — downstream hooks still see it). */
  delete(path: string): void;
  /** All paths currently present. */
  keys(): string[];
}

export interface PostgresDatabase {
  engine: string;
  instanceClass: string;
  multiAz?: boolean;
  storageGb: number;
}

export interface PostgresParams {
  role?: string;
}

export interface PostgresDependentHookContext {
  /** This kind's resolved resource. */
  self: Resource<SecretSpec, Dependency>;
  /** The consumer resource that declared a dependency on us. */
  consumer: Resource<PostgresSpec>;
  /** Path of the consumer resource file being rendered, relative
   *  to the veil project root. */
  path: string;
  /** Params the consumer supplied for this dependency. */
  params: PostgresParams;
  vars: RegistryVariables;
  root: string;
  std: Std;
  os: Os;
  fetch: Fetch;
}

export interface PostgresDependentHook {
  /** Runs after the consumer's render hooks complete. Mutates the
   *  consumer's bundle to wire it up against this resource. */
  render(ctx: PostgresDependentHookContext, fs: PostgresFS): PostgresFS | void | Promise<PostgresFS | void>;
}

