// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: veil/v1/compiled.proto

package veilv1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// CompiledKind is the compiled output of `veil build` for a single kind. It
// bundles every source file's contents and every hook's minified code into
// a single document, so rendering does not need access to the original
// filesystem.
type CompiledKind struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Name of the kind (matches Kind.name).
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Source files keyed by path relative to the kind directory. Values are
	// the raw file contents.
	Sources map[string]string `protobuf:"bytes,2,rep,name=sources,proto3" json:"sources,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Compiled hooks grouped by lifecycle point (matches Kind.hooks).
	Hooks *CompiledHooks `protobuf:"bytes,3,opt,name=hooks,proto3" json:"hooks,omitempty"`
	// Input variable declarations copied from veil.json. Consumers resolve
	// values from --var flags, VEIL_VAR_* env vars, or the declared default.
	Variables     map[string]*Variable `protobuf:"bytes,4,rep,name=variables,proto3" json:"variables,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompiledKind) Reset() {
	*x = CompiledKind{}
	mi := &file_veil_v1_compiled_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompiledKind) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompiledKind) ProtoMessage() {}

func (x *CompiledKind) ProtoReflect() protoreflect.Message {
	mi := &file_veil_v1_compiled_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompiledKind.ProtoReflect.Descriptor instead.
func (*CompiledKind) Descriptor() ([]byte, []int) {
	return file_veil_v1_compiled_proto_rawDescGZIP(), []int{0}
}

func (x *CompiledKind) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CompiledKind) GetSources() map[string]string {
	if x != nil {
		return x.Sources
	}
	return nil
}

func (x *CompiledKind) GetHooks() *CompiledHooks {
	if x != nil {
		return x.Hooks
	}
	return nil
}

func (x *CompiledKind) GetVariables() map[string]*Variable {
	if x != nil {
		return x.Variables
	}
	return nil
}

// CompiledHooks mirrors Kind.Hooks but holds compiled/bundled hook entries
// rather than paths.
type CompiledHooks struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Compiled hooks that run during `veil render`, in declaration order.
	Render        []*CompiledHook `protobuf:"bytes,1,rep,name=render,proto3" json:"render,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompiledHooks) Reset() {
	*x = CompiledHooks{}
	mi := &file_veil_v1_compiled_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompiledHooks) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompiledHooks) ProtoMessage() {}

func (x *CompiledHooks) ProtoReflect() protoreflect.Message {
	mi := &file_veil_v1_compiled_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompiledHooks.ProtoReflect.Descriptor instead.
func (*CompiledHooks) Descriptor() ([]byte, []int) {
	return file_veil_v1_compiled_proto_rawDescGZIP(), []int{1}
}

func (x *CompiledHooks) GetRender() []*CompiledHook {
	if x != nil {
		return x.Render
	}
	return nil
}

// CompiledRegistry is the top-level index written to <out>/registry.json by
// `veil build`. It maps kind name → entry describing how to find that kind's
// compiled artifacts. Consumers (e.g. `veil render`) read this to discover
// which kinds are available in a build artifact.
type CompiledRegistry struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Kind name → entry pointing at the compiled kind document and its schema.
	// All paths are resolved against the registry.json's own directory.
	Kinds         map[string]*CompiledRegistryEntry `protobuf:"bytes,1,rep,name=kinds,proto3" json:"kinds,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompiledRegistry) Reset() {
	*x = CompiledRegistry{}
	mi := &file_veil_v1_compiled_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompiledRegistry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompiledRegistry) ProtoMessage() {}

func (x *CompiledRegistry) ProtoReflect() protoreflect.Message {
	mi := &file_veil_v1_compiled_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompiledRegistry.ProtoReflect.Descriptor instead.
func (*CompiledRegistry) Descriptor() ([]byte, []int) {
	return file_veil_v1_compiled_proto_rawDescGZIP(), []int{2}
}

func (x *CompiledRegistry) GetKinds() map[string]*CompiledRegistryEntry {
	if x != nil {
		return x.Kinds
	}
	return nil
}

// CompiledRegistryEntry describes a single kind in a CompiledRegistry.
type CompiledRegistryEntry struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Name of the kind (matches the map key and CompiledKind.name).
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Relative path to the compiled kind.json (e.g. "./worker/kind.json").
	Path string `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	// Relative path to the kind's composite resource schema
	// (e.g. "./worker/kind.schema.json").
	Schema        string `protobuf:"bytes,3,opt,name=schema,proto3" json:"schema,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompiledRegistryEntry) Reset() {
	*x = CompiledRegistryEntry{}
	mi := &file_veil_v1_compiled_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompiledRegistryEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompiledRegistryEntry) ProtoMessage() {}

func (x *CompiledRegistryEntry) ProtoReflect() protoreflect.Message {
	mi := &file_veil_v1_compiled_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompiledRegistryEntry.ProtoReflect.Descriptor instead.
func (*CompiledRegistryEntry) Descriptor() ([]byte, []int) {
	return file_veil_v1_compiled_proto_rawDescGZIP(), []int{3}
}

func (x *CompiledRegistryEntry) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CompiledRegistryEntry) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *CompiledRegistryEntry) GetSchema() string {
	if x != nil {
		return x.Schema
	}
	return ""
}

// CompiledHook is a single hook bundled and minified from its TS/JS source,
// with all of its imports resolved and inlined.
type CompiledHook struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Relative path from the kind directory (e.g. "hooks/hello-world.ts").
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Minified JavaScript bundle, ES module format.
	Content       string `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompiledHook) Reset() {
	*x = CompiledHook{}
	mi := &file_veil_v1_compiled_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompiledHook) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompiledHook) ProtoMessage() {}

func (x *CompiledHook) ProtoReflect() protoreflect.Message {
	mi := &file_veil_v1_compiled_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompiledHook.ProtoReflect.Descriptor instead.
func (*CompiledHook) Descriptor() ([]byte, []int) {
	return file_veil_v1_compiled_proto_rawDescGZIP(), []int{4}
}

func (x *CompiledHook) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CompiledHook) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

var File_veil_v1_compiled_proto protoreflect.FileDescriptor

const file_veil_v1_compiled_proto_rawDesc = "" +
	"\n" +
	"\x16veil/v1/compiled.proto\x12\aveil.v1\x1a\x1bbuf/validate/validate.proto\x1a\x14veil/v1/config.proto\"\xeb\x02\n" +
	"\fCompiledKind\x12\x1e\n" +
	"\x04name\x18\x01 \x01(\tB\n" +
	"\xbaH\a\xc8\x01\x01r\x02\x10\x01R\x04name\x12<\n" +
	"\asources\x18\x02 \x03(\v2\".veil.v1.CompiledKind.SourcesEntryR\asources\x12,\n" +
	"\x05hooks\x18\x03 \x01(\v2\x16.veil.v1.CompiledHooksR\x05hooks\x12B\n" +
	"\tvariables\x18\x04 \x03(\v2$.veil.v1.CompiledKind.VariablesEntryR\tvariables\x1a:\n" +
	"\fSourcesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1aO\n" +
	"\x0eVariablesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12'\n" +
	"\x05value\x18\x02 \x01(\v2\x11.veil.v1.VariableR\x05value:\x028\x01\">\n" +
	"\rCompiledHooks\x12-\n" +
	"\x06render\x18\x01 \x03(\v2\x15.veil.v1.CompiledHookR\x06render\"\xa8\x01\n" +
	"\x10CompiledRegistry\x12:\n" +
	"\x05kinds\x18\x01 \x03(\v2$.veil.v1.CompiledRegistry.KindsEntryR\x05kinds\x1aX\n" +
	"\n" +
	"KindsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x124\n" +
	"\x05value\x18\x02 \x01(\v2\x1e.veil.v1.CompiledRegistryEntryR\x05value:\x028\x01\"{\n" +
	"\x15CompiledRegistryEntry\x12\x1e\n" +
	"\x04name\x18\x01 \x01(\tB\n" +
	"\xbaH\a\xc8\x01\x01r\x02\x10\x01R\x04name\x12\x1e\n" +
	"\x04path\x18\x02 \x01(\tB\n" +
	"\xbaH\a\xc8\x01\x01r\x02\x10\x01R\x04path\x12\"\n" +
	"\x06schema\x18\x03 \x01(\tB\n" +
	"\xbaH\a\xc8\x01\x01r\x02\x10\x01R\x06schema\"T\n" +
	"\fCompiledHook\x12\x1e\n" +
	"\x04name\x18\x01 \x01(\tB\n" +
	"\xbaH\a\xc8\x01\x01r\x02\x10\x01R\x04name\x12$\n" +
	"\acontent\x18\x02 \x01(\tB\n" +
	"\xbaH\a\xc8\x01\x01r\x02\x10\x01R\acontentB\x87\x01\n" +
	"\vcom.veil.v1B\rCompiledProtoP\x01Z,github.com/vercel/veil/api/go/veil/v1;veilv1\xa2\x02\x03VXX\xaa\x02\aVeil.V1\xca\x02\aVeil\\V1\xe2\x02\x13Veil\\V1\\GPBMetadata\xea\x02\bVeil::V1b\x06proto3"

var (
	file_veil_v1_compiled_proto_rawDescOnce sync.Once
	file_veil_v1_compiled_proto_rawDescData []byte
)

func file_veil_v1_compiled_proto_rawDescGZIP() []byte {
	file_veil_v1_compiled_proto_rawDescOnce.Do(func() {
		file_veil_v1_compiled_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_veil_v1_compiled_proto_rawDesc), len(file_veil_v1_compiled_proto_rawDesc)))
	})
	return file_veil_v1_compiled_proto_rawDescData
}

var file_veil_v1_compiled_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_veil_v1_compiled_proto_goTypes = []any{
	(*CompiledKind)(nil),          // 0: veil.v1.CompiledKind
	(*CompiledHooks)(nil),         // 1: veil.v1.CompiledHooks
	(*CompiledRegistry)(nil),      // 2: veil.v1.CompiledRegistry
	(*CompiledRegistryEntry)(nil), // 3: veil.v1.CompiledRegistryEntry
	(*CompiledHook)(nil),          // 4: veil.v1.CompiledHook
	nil,                           // 5: veil.v1.CompiledKind.SourcesEntry
	nil,                           // 6: veil.v1.CompiledKind.VariablesEntry
	nil,                           // 7: veil.v1.CompiledRegistry.KindsEntry
	(*Variable)(nil),              // 8: veil.v1.Variable
}
var file_veil_v1_compiled_proto_depIdxs = []int32{
	5, // 0: veil.v1.CompiledKind.sources:type_name -> veil.v1.CompiledKind.SourcesEntry
	1, // 1: veil.v1.CompiledKind.hooks:type_name -> veil.v1.CompiledHooks
	6, // 2: veil.v1.CompiledKind.variables:type_name -> veil.v1.CompiledKind.VariablesEntry
	4, // 3: veil.v1.CompiledHooks.render:type_name -> veil.v1.CompiledHook
	7, // 4: veil.v1.CompiledRegistry.kinds:type_name -> veil.v1.CompiledRegistry.KindsEntry
	8, // 5: veil.v1.CompiledKind.VariablesEntry.value:type_name -> veil.v1.Variable
	3, // 6: veil.v1.CompiledRegistry.KindsEntry.value:type_name -> veil.v1.CompiledRegistryEntry
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_veil_v1_compiled_proto_init() }
func file_veil_v1_compiled_proto_init() {
	if File_veil_v1_compiled_proto != nil {
		return
	}
	file_veil_v1_config_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_veil_v1_compiled_proto_rawDesc), len(file_veil_v1_compiled_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_veil_v1_compiled_proto_goTypes,
		DependencyIndexes: file_veil_v1_compiled_proto_depIdxs,
		MessageInfos:      file_veil_v1_compiled_proto_msgTypes,
	}.Build()
	File_veil_v1_compiled_proto = out.File
	file_veil_v1_compiled_proto_goTypes = nil
	file_veil_v1_compiled_proto_depIdxs = nil
}
