// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: veil/v1/config.proto

package veilv1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// VeilConfig is the contents of .veil/veil.json.
type VeilConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Relative or absolute paths to kind definition files.
	Kinds []string `protobuf:"bytes,1,rep,name=kinds,proto3" json:"kinds,omitempty"`
	// User-defined input variables keyed by name. Values are provided at
	// render time via --var flags or VEIL_VAR_<NAME> environment variables.
	Variables map[string]*Variable `protobuf:"bytes,2,rep,name=variables,proto3" json:"variables,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Paths to additional compiled registry.json files to load at render
	// time. Local builds are discovered automatically; use this to wire in
	// shared or externally-distributed registries.
	Registries    []string `protobuf:"bytes,3,rep,name=registries,proto3" json:"registries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VeilConfig) Reset() {
	*x = VeilConfig{}
	mi := &file_veil_v1_config_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VeilConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VeilConfig) ProtoMessage() {}

func (x *VeilConfig) ProtoReflect() protoreflect.Message {
	mi := &file_veil_v1_config_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VeilConfig.ProtoReflect.Descriptor instead.
func (*VeilConfig) Descriptor() ([]byte, []int) {
	return file_veil_v1_config_proto_rawDescGZIP(), []int{0}
}

func (x *VeilConfig) GetKinds() []string {
	if x != nil {
		return x.Kinds
	}
	return nil
}

func (x *VeilConfig) GetVariables() map[string]*Variable {
	if x != nil {
		return x.Variables
	}
	return nil
}

func (x *VeilConfig) GetRegistries() []string {
	if x != nil {
		return x.Registries
	}
	return nil
}

// Variable declares a named input available to overlay CEL expressions.
type Variable struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Declared type: "string", "number", or "bool".
	Type string `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	// Optional default. If omitted, the variable is required at render time.
	// Must be a scalar matching the declared type.
	Default *structpb.Value `protobuf:"bytes,2,opt,name=default,proto3,oneof" json:"default,omitempty"`
	// Optional human-readable description. Rendered as a JSDoc comment on
	// the field in the generated veil-types.ts RegistryVariables interface
	// so hook authors get inline documentation at their IDE cursor.
	Description *string `protobuf:"bytes,3,opt,name=description,proto3,oneof" json:"description,omitempty"`
	// Optional set of permitted values. Only valid for `string` and `number`
	// types. When present, the generated TypeScript field becomes a union
	// ("a" | "b" | "c") instead of the broad scalar type, and values
	// supplied via --var or VEIL_VAR_* are rejected at render time unless
	// they match one of the listed entries.
	Enum          []*structpb.Value `protobuf:"bytes,4,rep,name=enum,proto3" json:"enum,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Variable) Reset() {
	*x = Variable{}
	mi := &file_veil_v1_config_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Variable) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Variable) ProtoMessage() {}

func (x *Variable) ProtoReflect() protoreflect.Message {
	mi := &file_veil_v1_config_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Variable.ProtoReflect.Descriptor instead.
func (*Variable) Descriptor() ([]byte, []int) {
	return file_veil_v1_config_proto_rawDescGZIP(), []int{1}
}

func (x *Variable) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Variable) GetDefault() *structpb.Value {
	if x != nil {
		return x.Default
	}
	return nil
}

func (x *Variable) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *Variable) GetEnum() []*structpb.Value {
	if x != nil {
		return x.Enum
	}
	return nil
}

// Kind defines a resource type in the registry (e.g. "service", "cron").
type Kind struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The name of this kind (e.g. "service", "cron").
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Source configuration files that make up the kind.
	Sources []string `protobuf:"bytes,2,rep,name=sources,proto3" json:"sources,omitempty"`
	// Hook code files grouped by lifecycle point.
	Hooks *Hooks `protobuf:"bytes,3,opt,name=hooks,proto3" json:"hooks,omitempty"`
	// Path to the JSON Schema that defines the spec shape.
	Schema        string `protobuf:"bytes,5,opt,name=schema,proto3" json:"schema,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Kind) Reset() {
	*x = Kind{}
	mi := &file_veil_v1_config_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Kind) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Kind) ProtoMessage() {}

func (x *Kind) ProtoReflect() protoreflect.Message {
	mi := &file_veil_v1_config_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Kind.ProtoReflect.Descriptor instead.
func (*Kind) Descriptor() ([]byte, []int) {
	return file_veil_v1_config_proto_rawDescGZIP(), []int{2}
}

func (x *Kind) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Kind) GetSources() []string {
	if x != nil {
		return x.Sources
	}
	return nil
}

func (x *Kind) GetHooks() *Hooks {
	if x != nil {
		return x.Hooks
	}
	return nil
}

func (x *Kind) GetSchema() string {
	if x != nil {
		return x.Schema
	}
	return ""
}

// Hooks groups a kind's hook files by lifecycle point. Each field is an
// ordered list; the order determines invocation order at that lifecycle
// point. Additional lifecycle points will be added as fields on this
// message so the kind.json shape can extend without breaking changes.
type Hooks struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Hooks run during `veil render` (each exports a Hook whose optional
	// `renderHook(ctx, fs)` transforms the bundle).
	Render        []string `protobuf:"bytes,1,rep,name=render,proto3" json:"render,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Hooks) Reset() {
	*x = Hooks{}
	mi := &file_veil_v1_config_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Hooks) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Hooks) ProtoMessage() {}

func (x *Hooks) ProtoReflect() protoreflect.Message {
	mi := &file_veil_v1_config_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Hooks.ProtoReflect.Descriptor instead.
func (*Hooks) Descriptor() ([]byte, []int) {
	return file_veil_v1_config_proto_rawDescGZIP(), []int{3}
}

func (x *Hooks) GetRender() []string {
	if x != nil {
		return x.Render
	}
	return nil
}

var File_veil_v1_config_proto protoreflect.FileDescriptor

const file_veil_v1_config_proto_rawDesc = "" +
	"\n" +
	"\x14veil/v1/config.proto\x12\aveil.v1\x1a\x1bbuf/validate/validate.proto\x1a\x1cgoogle/protobuf/struct.proto\"\xdf\x01\n" +
	"\n" +
	"VeilConfig\x12\x1e\n" +
	"\x05kinds\x18\x01 \x03(\tB\b\xbaH\x05\x92\x01\x02\b\x01R\x05kinds\x12@\n" +
	"\tvariables\x18\x02 \x03(\v2\".veil.v1.VeilConfig.VariablesEntryR\tvariables\x12\x1e\n" +
	"\n" +
	"registries\x18\x03 \x03(\tR\n" +
	"registries\x1aO\n" +
	"\x0eVariablesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12'\n" +
	"\x05value\x18\x02 \x01(\v2\x11.veil.v1.VariableR\x05value:\x028\x01\"\xe6\x01\n" +
	"\bVariable\x124\n" +
	"\x04type\x18\x01 \x01(\tB \xbaH\x1d\xc8\x01\x01r\x182\x16^(string|number|bool)$R\x04type\x125\n" +
	"\adefault\x18\x02 \x01(\v2\x16.google.protobuf.ValueH\x00R\adefault\x88\x01\x01\x12%\n" +
	"\vdescription\x18\x03 \x01(\tH\x01R\vdescription\x88\x01\x01\x12*\n" +
	"\x04enum\x18\x04 \x03(\v2\x16.google.protobuf.ValueR\x04enumB\n" +
	"\n" +
	"\b_defaultB\x0e\n" +
	"\f_description\"\x88\x01\n" +
	"\x04Kind\x12\x1e\n" +
	"\x04name\x18\x01 \x01(\tB\n" +
	"\xbaH\a\xc8\x01\x01r\x02\x10\x01R\x04name\x12\"\n" +
	"\asources\x18\x02 \x03(\tB\b\xbaH\x05\x92\x01\x02\b\x01R\asources\x12$\n" +
	"\x05hooks\x18\x03 \x01(\v2\x0e.veil.v1.HooksR\x05hooks\x12\x16\n" +
	"\x06schema\x18\x05 \x01(\tR\x06schema\"\x1f\n" +
	"\x05Hooks\x12\x16\n" +
	"\x06render\x18\x01 \x03(\tR\x06renderB\x85\x01\n" +
	"\vcom.veil.v1B\vConfigProtoP\x01Z,github.com/vercel/veil/api/go/veil/v1;veilv1\xa2\x02\x03VXX\xaa\x02\aVeil.V1\xca\x02\aVeil\\V1\xe2\x02\x13Veil\\V1\\GPBMetadata\xea\x02\bVeil::V1b\x06proto3"

var (
	file_veil_v1_config_proto_rawDescOnce sync.Once
	file_veil_v1_config_proto_rawDescData []byte
)

func file_veil_v1_config_proto_rawDescGZIP() []byte {
	file_veil_v1_config_proto_rawDescOnce.Do(func() {
		file_veil_v1_config_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_veil_v1_config_proto_rawDesc), len(file_veil_v1_config_proto_rawDesc)))
	})
	return file_veil_v1_config_proto_rawDescData
}

var file_veil_v1_config_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_veil_v1_config_proto_goTypes = []any{
	(*VeilConfig)(nil),     // 0: veil.v1.VeilConfig
	(*Variable)(nil),       // 1: veil.v1.Variable
	(*Kind)(nil),           // 2: veil.v1.Kind
	(*Hooks)(nil),          // 3: veil.v1.Hooks
	nil,                    // 4: veil.v1.VeilConfig.VariablesEntry
	(*structpb.Value)(nil), // 5: google.protobuf.Value
}
var file_veil_v1_config_proto_depIdxs = []int32{
	4, // 0: veil.v1.VeilConfig.variables:type_name -> veil.v1.VeilConfig.VariablesEntry
	5, // 1: veil.v1.Variable.default:type_name -> google.protobuf.Value
	5, // 2: veil.v1.Variable.enum:type_name -> google.protobuf.Value
	3, // 3: veil.v1.Kind.hooks:type_name -> veil.v1.Hooks
	1, // 4: veil.v1.VeilConfig.VariablesEntry.value:type_name -> veil.v1.Variable
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_veil_v1_config_proto_init() }
func file_veil_v1_config_proto_init() {
	if File_veil_v1_config_proto != nil {
		return
	}
	file_veil_v1_config_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_veil_v1_config_proto_rawDesc), len(file_veil_v1_config_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_veil_v1_config_proto_goTypes,
		DependencyIndexes: file_veil_v1_config_proto_depIdxs,
		MessageInfos:      file_veil_v1_config_proto_msgTypes,
	}.Build()
	File_veil_v1_config_proto = out.File
	file_veil_v1_config_proto_goTypes = nil
	file_veil_v1_config_proto_depIdxs = nil
}
