// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: veil/v1/config.proto

package veilv1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Enum is the set of legal types for a declared variable. Values are
// intentionally lowercase to preserve the existing JSON wire format —
// protojson serializes enum values as their declared identifier, so
// anything else would change every veil.json on disk.
//
// buf:lint:ignore ENUM_VALUE_UPPER_SNAKE_CASE
// buf:lint:ignore ENUM_VALUE_PREFIX
// buf:lint:ignore ENUM_ZERO_VALUE_SUFFIX
type VariableType_Enum int32

const (
	// buf:lint:ignore ENUM_VALUE_UPPER_SNAKE_CASE
	// buf:lint:ignore ENUM_VALUE_PREFIX
	// buf:lint:ignore ENUM_ZERO_VALUE_SUFFIX
	VariableType_unspecified VariableType_Enum = 0
	// buf:lint:ignore ENUM_VALUE_UPPER_SNAKE_CASE
	// buf:lint:ignore ENUM_VALUE_PREFIX
	VariableType_string VariableType_Enum = 1
	// buf:lint:ignore ENUM_VALUE_UPPER_SNAKE_CASE
	// buf:lint:ignore ENUM_VALUE_PREFIX
	VariableType_number VariableType_Enum = 2
	// buf:lint:ignore ENUM_VALUE_UPPER_SNAKE_CASE
	// buf:lint:ignore ENUM_VALUE_PREFIX
	VariableType_bool VariableType_Enum = 3
)

// Enum value maps for VariableType_Enum.
var (
	VariableType_Enum_name = map[int32]string{
		0: "unspecified",
		1: "string",
		2: "number",
		3: "bool",
	}
	VariableType_Enum_value = map[string]int32{
		"unspecified": 0,
		"string":      1,
		"number":      2,
		"bool":        3,
	}
)

func (x VariableType_Enum) Enum() *VariableType_Enum {
	p := new(VariableType_Enum)
	*p = x
	return p
}

func (x VariableType_Enum) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (VariableType_Enum) Descriptor() protoreflect.EnumDescriptor {
	return file_veil_v1_config_proto_enumTypes[0].Descriptor()
}

func (VariableType_Enum) Type() protoreflect.EnumType {
	return &file_veil_v1_config_proto_enumTypes[0]
}

func (x VariableType_Enum) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use VariableType_Enum.Descriptor instead.
func (VariableType_Enum) EnumDescriptor() ([]byte, []int) {
	return file_veil_v1_config_proto_rawDescGZIP(), []int{2, 0}
}

// VeilConfigDefinition is the contents of .veil/veil.json — the
// hand-authored source-side project configuration. The "Definition"
// suffix marks it as a local-file shape; types under registry.proto
// (Kind, Registry, …) are the corresponding published forms.
type VeilConfigDefinition struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Relative or absolute paths to kind definition files.
	Kinds []string `protobuf:"bytes,1,rep,name=kinds,proto3" json:"kinds,omitempty"`
	// User-defined input variables keyed by name. Values are provided at
	// render time via --var flags or VEIL_VAR_<NAME> environment variables.
	Variables map[string]*Variable `protobuf:"bytes,2,rep,name=variables,proto3" json:"variables,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Aliased registry sources keyed by alias. The empty-string alias
	// (`""`) is the default registry: kind references with no `<alias>/`
	// prefix resolve there. Named aliases can be any string and are used
	// verbatim in references — declaring
	// `"acme": "./vendor/acme/registry.json"` lets resources reference
	// its kinds as `acme/<kind>`. The `@`-prefixed convention (e.g.
	// `"@scope": "..."` referenced as `@scope/<kind>`) is supported but
	// not required — the alias is treated as opaque text. Values are
	// paths to compiled registry.json files (or URLs, when the loader
	// supports them).
	Registries map[string]string `protobuf:"bytes,3,rep,name=registries,proto3" json:"registries,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Where to find the resource JSON files that make up the project's
	// catalog. Used at render time to resolve dependency targets.
	ResourceDiscovery *ResourceDiscovery `protobuf:"bytes,4,opt,name=resource_discovery,json=resourceDiscovery,proto3" json:"resource_discovery,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *VeilConfigDefinition) Reset() {
	*x = VeilConfigDefinition{}
	mi := &file_veil_v1_config_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VeilConfigDefinition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VeilConfigDefinition) ProtoMessage() {}

func (x *VeilConfigDefinition) ProtoReflect() protoreflect.Message {
	mi := &file_veil_v1_config_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VeilConfigDefinition.ProtoReflect.Descriptor instead.
func (*VeilConfigDefinition) Descriptor() ([]byte, []int) {
	return file_veil_v1_config_proto_rawDescGZIP(), []int{0}
}

func (x *VeilConfigDefinition) GetKinds() []string {
	if x != nil {
		return x.Kinds
	}
	return nil
}

func (x *VeilConfigDefinition) GetVariables() map[string]*Variable {
	if x != nil {
		return x.Variables
	}
	return nil
}

func (x *VeilConfigDefinition) GetRegistries() map[string]string {
	if x != nil {
		return x.Registries
	}
	return nil
}

func (x *VeilConfigDefinition) GetResourceDiscovery() *ResourceDiscovery {
	if x != nil {
		return x.ResourceDiscovery
	}
	return nil
}

// ResourceDiscovery declares how `veil render` builds its catalog of
// resources for dependency resolution. Each path is a glob expression
// (`**` matches across directory boundaries via the doublestar library)
// pointing at the JSON files that should be indexed. Relative patterns
// resolve against the veil.json directory.
type ResourceDiscovery struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Glob patterns identifying resource JSON files. Files that don't
	// parse as a Resource shape (overlays, fragments, schemas) are
	// skipped silently; duplicate (kind, name) pairs across matches are
	// rejected.
	Paths         []string `protobuf:"bytes,1,rep,name=paths,proto3" json:"paths,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResourceDiscovery) Reset() {
	*x = ResourceDiscovery{}
	mi := &file_veil_v1_config_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceDiscovery) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceDiscovery) ProtoMessage() {}

func (x *ResourceDiscovery) ProtoReflect() protoreflect.Message {
	mi := &file_veil_v1_config_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceDiscovery.ProtoReflect.Descriptor instead.
func (*ResourceDiscovery) Descriptor() ([]byte, []int) {
	return file_veil_v1_config_proto_rawDescGZIP(), []int{1}
}

func (x *ResourceDiscovery) GetPaths() []string {
	if x != nil {
		return x.Paths
	}
	return nil
}

// VariableType is a wrapper message that holds the Variable.type enum.
// Wrapping it in a message gives the Go-generated identifiers a clean
// nested form (VariableType_Enum_*) and lets the JSON wire format use
// lowercase value names ("string", "number", "bool") that match the
// veil.json shape users have been writing since day one.
type VariableType struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VariableType) Reset() {
	*x = VariableType{}
	mi := &file_veil_v1_config_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VariableType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VariableType) ProtoMessage() {}

func (x *VariableType) ProtoReflect() protoreflect.Message {
	mi := &file_veil_v1_config_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VariableType.ProtoReflect.Descriptor instead.
func (*VariableType) Descriptor() ([]byte, []int) {
	return file_veil_v1_config_proto_rawDescGZIP(), []int{2}
}

// Variable declares a named input available to overlay regex matches
// (and to hooks via the render context). Lives in both the local
// VeilConfigDefinition and the published Kind (carried verbatim
// through compilation), so it has no Definition suffix — the same
// shape applies in both contexts.
type Variable struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Declared type. Must be one of the legal VariableType.Enum values
	// (the `unspecified` zero is rejected at load time).
	Type VariableType_Enum `protobuf:"varint,1,opt,name=type,proto3,enum=veil.v1.VariableType_Enum" json:"type,omitempty"`
	// Optional default. If omitted, the variable is required at render time.
	// Must be a scalar matching the declared type.
	Default *structpb.Value `protobuf:"bytes,2,opt,name=default,proto3,oneof" json:"default,omitempty"`
	// Optional human-readable description. Rendered as a JSDoc comment on
	// the field in the generated veil-types.ts RegistryVariables interface
	// so hook authors get inline documentation at their IDE cursor.
	Description *string `protobuf:"bytes,3,opt,name=description,proto3,oneof" json:"description,omitempty"`
	// Optional set of permitted values. Only valid for `string` and `number`
	// types. When present, the generated TypeScript field becomes a union
	// ("a" | "b" | "c") instead of the broad scalar type, and values
	// supplied via --var or VEIL_VAR_* are rejected at render time unless
	// they match one of the listed entries.
	Enum          []*structpb.Value `protobuf:"bytes,4,rep,name=enum,proto3" json:"enum,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Variable) Reset() {
	*x = Variable{}
	mi := &file_veil_v1_config_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Variable) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Variable) ProtoMessage() {}

func (x *Variable) ProtoReflect() protoreflect.Message {
	mi := &file_veil_v1_config_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Variable.ProtoReflect.Descriptor instead.
func (*Variable) Descriptor() ([]byte, []int) {
	return file_veil_v1_config_proto_rawDescGZIP(), []int{3}
}

func (x *Variable) GetType() VariableType_Enum {
	if x != nil {
		return x.Type
	}
	return VariableType_unspecified
}

func (x *Variable) GetDefault() *structpb.Value {
	if x != nil {
		return x.Default
	}
	return nil
}

func (x *Variable) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *Variable) GetEnum() []*structpb.Value {
	if x != nil {
		return x.Enum
	}
	return nil
}

// KindDefinition is a hand-authored kind.json — the source-side shape
// that `veil build` compiles into a published Kind (registry.proto).
type KindDefinition struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The name of this kind (e.g. "service", "cron"). Must start with a
	// lowercase letter and contain only lowercase letters, digits, `-`,
	// and `_` — the same convention enforced by `veil new kind`.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Source configuration files that make up the kind. May be empty —
	// a kind with no sources is valid (it's the bare template plus
	// whatever its hooks add at render time).
	Sources []string `protobuf:"bytes,2,rep,name=sources,proto3" json:"sources,omitempty"`
	// Hook code files grouped by lifecycle point. The dependents block —
	// the per-consumer hooks that fire when another kind declares a
	// dependency on this one — also lives under `hooks`, since it is
	// ultimately just another hook lifecycle.
	Hooks *HooksDefinition `protobuf:"bytes,3,opt,name=hooks,proto3" json:"hooks,omitempty"`
	// Path to the JSON Schema that defines the spec shape.
	Schema        string `protobuf:"bytes,5,opt,name=schema,proto3" json:"schema,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KindDefinition) Reset() {
	*x = KindDefinition{}
	mi := &file_veil_v1_config_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KindDefinition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KindDefinition) ProtoMessage() {}

func (x *KindDefinition) ProtoReflect() protoreflect.Message {
	mi := &file_veil_v1_config_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KindDefinition.ProtoReflect.Descriptor instead.
func (*KindDefinition) Descriptor() ([]byte, []int) {
	return file_veil_v1_config_proto_rawDescGZIP(), []int{4}
}

func (x *KindDefinition) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *KindDefinition) GetSources() []string {
	if x != nil {
		return x.Sources
	}
	return nil
}

func (x *KindDefinition) GetHooks() *HooksDefinition {
	if x != nil {
		return x.Hooks
	}
	return nil
}

func (x *KindDefinition) GetSchema() string {
	if x != nil {
		return x.Schema
	}
	return ""
}

// HooksDefinition groups a kind's hook files by lifecycle point. Each
// field is an ordered list; the order determines invocation order at
// that lifecycle point. Additional lifecycle points will be added as
// fields on this message so the kind.json shape can extend without
// breaking changes.
type HooksDefinition struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Hooks run during `veil render` (each exports a Hook whose optional
	// `renderHook(ctx, fs)` transforms the bundle). Each entry is an
	// object with a required `path` plus optional `access` declaring the
	// host resources the hook may read.
	Render []*RenderHookDefinition `protobuf:"bytes,1,rep,name=render,proto3" json:"render,omitempty"`
	// Per-consumer dependent hooks. Each entry binds a consumer kind to
	// hook(s) that run when a resource of that kind declares a
	// dependency on this one, plus the params schema the consumer must
	// supply. See SPEC.md "Dependencies" for the full design.
	Dependents    []*DependentDefinition `protobuf:"bytes,2,rep,name=dependents,proto3" json:"dependents,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HooksDefinition) Reset() {
	*x = HooksDefinition{}
	mi := &file_veil_v1_config_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HooksDefinition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HooksDefinition) ProtoMessage() {}

func (x *HooksDefinition) ProtoReflect() protoreflect.Message {
	mi := &file_veil_v1_config_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HooksDefinition.ProtoReflect.Descriptor instead.
func (*HooksDefinition) Descriptor() ([]byte, []int) {
	return file_veil_v1_config_proto_rawDescGZIP(), []int{5}
}

func (x *HooksDefinition) GetRender() []*RenderHookDefinition {
	if x != nil {
		return x.Render
	}
	return nil
}

func (x *HooksDefinition) GetDependents() []*DependentDefinition {
	if x != nil {
		return x.Dependents
	}
	return nil
}

// RenderHookDefinition is a single render-hook entry in kind.json: a
// path to the hook source file plus optional `access` declaring the
// host resources the hook may read.
type RenderHookDefinition struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Path to the hook source file. Resolved relative to the enclosing
	// kind.json file.
	Path string `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	// Optional declaration of host resources this hook needs (env vars,
	// and eventually filesystem / network as they're added).
	Access        *HookAccess `protobuf:"bytes,2,opt,name=access,proto3" json:"access,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RenderHookDefinition) Reset() {
	*x = RenderHookDefinition{}
	mi := &file_veil_v1_config_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RenderHookDefinition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RenderHookDefinition) ProtoMessage() {}

func (x *RenderHookDefinition) ProtoReflect() protoreflect.Message {
	mi := &file_veil_v1_config_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RenderHookDefinition.ProtoReflect.Descriptor instead.
func (*RenderHookDefinition) Descriptor() ([]byte, []int) {
	return file_veil_v1_config_proto_rawDescGZIP(), []int{6}
}

func (x *RenderHookDefinition) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *RenderHookDefinition) GetAccess() *HookAccess {
	if x != nil {
		return x.Access
	}
	return nil
}

// HookAccess declares the host resources a hook is allowed to reach. The
// runner enforces these at render time: required env vars must be
// present on the host, and the hook receives only what it declared.
type HookAccess struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Environment variables the hook intends to read. Each entry must
	// describe both the name and why it's needed; the description is
	// surfaced in pre-flight error messages when the var is missing.
	Env           []*EnvAccess `protobuf:"bytes,1,rep,name=env,proto3" json:"env,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HookAccess) Reset() {
	*x = HookAccess{}
	mi := &file_veil_v1_config_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HookAccess) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HookAccess) ProtoMessage() {}

func (x *HookAccess) ProtoReflect() protoreflect.Message {
	mi := &file_veil_v1_config_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HookAccess.ProtoReflect.Descriptor instead.
func (*HookAccess) Descriptor() ([]byte, []int) {
	return file_veil_v1_config_proto_rawDescGZIP(), []int{7}
}

func (x *HookAccess) GetEnv() []*EnvAccess {
	if x != nil {
		return x.Env
	}
	return nil
}

// EnvAccess names a single host environment variable a hook needs.
type EnvAccess struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The env var being requested by the hook. Must match the conventions
	// for valid POSIX environment-variable identifiers.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// A brief description of what this key is used for and why. Surfaced
	// when the var is missing so the user can correct the issue.
	Description   string `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnvAccess) Reset() {
	*x = EnvAccess{}
	mi := &file_veil_v1_config_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnvAccess) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnvAccess) ProtoMessage() {}

func (x *EnvAccess) ProtoReflect() protoreflect.Message {
	mi := &file_veil_v1_config_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnvAccess.ProtoReflect.Descriptor instead.
func (*EnvAccess) Descriptor() ([]byte, []int) {
	return file_veil_v1_config_proto_rawDescGZIP(), []int{8}
}

func (x *EnvAccess) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *EnvAccess) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

// DependentDefinition declares a consumer kind that may depend on this
// kind, the hook file path(s) that run when such a dependency is
// rendered, and the JSON Schema describing the `params` the consumer
// must supply.
type DependentDefinition struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The consumer kind that may depend on this resource.
	Kind string `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty"`
	// Paths to hook files that run when a resource of `kind` declares a
	// dependency on this resource. At least one entry is required. Hooks
	// run in declaration order. Paths are resolved relative to the
	// enclosing kind.json file.
	Paths []string `protobuf:"bytes,2,rep,name=paths,proto3" json:"paths,omitempty"`
	// Path to the JSON Schema describing the `params` object that the
	// consumer must supply when declaring this dependency. Resolved
	// relative to the enclosing kind.json file.
	ParamsPath    string `protobuf:"bytes,3,opt,name=params_path,json=paramsPath,proto3" json:"params_path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DependentDefinition) Reset() {
	*x = DependentDefinition{}
	mi := &file_veil_v1_config_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DependentDefinition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DependentDefinition) ProtoMessage() {}

func (x *DependentDefinition) ProtoReflect() protoreflect.Message {
	mi := &file_veil_v1_config_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DependentDefinition.ProtoReflect.Descriptor instead.
func (*DependentDefinition) Descriptor() ([]byte, []int) {
	return file_veil_v1_config_proto_rawDescGZIP(), []int{9}
}

func (x *DependentDefinition) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *DependentDefinition) GetPaths() []string {
	if x != nil {
		return x.Paths
	}
	return nil
}

func (x *DependentDefinition) GetParamsPath() string {
	if x != nil {
		return x.ParamsPath
	}
	return ""
}

var File_veil_v1_config_proto protoreflect.FileDescriptor

const file_veil_v1_config_proto_rawDesc = "" +
	"\n" +
	"\x14veil/v1/config.proto\x12\aveil.v1\x1a\x1bbuf/validate/validate.proto\x1a\x1cgoogle/protobuf/struct.proto\"\xfa\x03\n" +
	"\x14VeilConfigDefinition\x12$\n" +
	"\x05kinds\x18\x01 \x03(\tB\x0e\xbaH\v\x92\x01\b\b\x01\"\x04r\x02\x10\x01R\x05kinds\x12p\n" +
	"\tvariables\x18\x02 \x03(\v2,.veil.v1.VeilConfigDefinition.VariablesEntryB$\xbaH!\x9a\x01\x1e\"\x1cr\x1a2\x18^[a-zA-Z_][a-zA-Z0-9_]*$R\tvariables\x12o\n" +
	"\n" +
	"registries\x18\x03 \x03(\v2-.veil.v1.VeilConfigDefinition.RegistriesEntryB \xbaH\x1d\xc8\x01\x01\x9a\x01\x17\"\x15r\x132\x11^([^.:/][^:/]*)?$R\n" +
	"registries\x12I\n" +
	"\x12resource_discovery\x18\x04 \x01(\v2\x1a.veil.v1.ResourceDiscoveryR\x11resourceDiscovery\x1aO\n" +
	"\x0eVariablesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12'\n" +
	"\x05value\x18\x02 \x01(\v2\x11.veil.v1.VariableR\x05value:\x028\x01\x1a=\n" +
	"\x0fRegistriesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"7\n" +
	"\x11ResourceDiscovery\x12\"\n" +
	"\x05paths\x18\x01 \x03(\tB\f\xbaH\t\x92\x01\x06\"\x04r\x02\x10\x01R\x05paths\"I\n" +
	"\fVariableType\"9\n" +
	"\x04Enum\x12\x0f\n" +
	"\vunspecified\x10\x00\x12\n" +
	"\n" +
	"\x06string\x10\x01\x12\n" +
	"\n" +
	"\x06number\x10\x02\x12\b\n" +
	"\x04bool\x10\x03\"\xea\x01\n" +
	"\bVariable\x128\n" +
	"\x04type\x18\x01 \x01(\x0e2\x1a.veil.v1.VariableType.EnumB\b\xbaH\x05\x82\x01\x02\x10\x01R\x04type\x125\n" +
	"\adefault\x18\x02 \x01(\v2\x16.google.protobuf.ValueH\x00R\adefault\x88\x01\x01\x12%\n" +
	"\vdescription\x18\x03 \x01(\tH\x01R\vdescription\x88\x01\x01\x12*\n" +
	"\x04enum\x18\x04 \x03(\v2\x16.google.protobuf.ValueR\x04enumB\n" +
	"\n" +
	"\b_defaultB\x0e\n" +
	"\f_description\"\xb4\x01\n" +
	"\x0eKindDefinition\x122\n" +
	"\x04name\x18\x01 \x01(\tB\x1e\xbaH\x1b\xc8\x01\x01r\x16\x10\x012\x12^[a-z][a-z0-9_-]*$R\x04name\x12&\n" +
	"\asources\x18\x02 \x03(\tB\f\xbaH\t\x92\x01\x06\"\x04r\x02\x10\x01R\asources\x12.\n" +
	"\x05hooks\x18\x03 \x01(\v2\x18.veil.v1.HooksDefinitionR\x05hooks\x12\x16\n" +
	"\x06schema\x18\x05 \x01(\tR\x06schema\"\x86\x01\n" +
	"\x0fHooksDefinition\x125\n" +
	"\x06render\x18\x01 \x03(\v2\x1d.veil.v1.RenderHookDefinitionR\x06render\x12<\n" +
	"\n" +
	"dependents\x18\x02 \x03(\v2\x1c.veil.v1.DependentDefinitionR\n" +
	"dependents\"c\n" +
	"\x14RenderHookDefinition\x12\x1e\n" +
	"\x04path\x18\x01 \x01(\tB\n" +
	"\xbaH\a\xc8\x01\x01r\x02\x10\x01R\x04path\x12+\n" +
	"\x06access\x18\x02 \x01(\v2\x13.veil.v1.HookAccessR\x06access\"2\n" +
	"\n" +
	"HookAccess\x12$\n" +
	"\x03env\x18\x01 \x03(\v2\x12.veil.v1.EnvAccessR\x03env\"s\n" +
	"\tEnvAccess\x128\n" +
	"\x04name\x18\x01 \x01(\tB$\xbaH!\xc8\x01\x01r\x1c\x10\x012\x18^[A-Za-z_][A-Za-z0-9_]*$R\x04name\x12,\n" +
	"\vdescription\x18\x02 \x01(\tB\n" +
	"\xbaH\a\xc8\x01\x01r\x02\x10\x01R\vdescription\"\x9c\x01\n" +
	"\x13DependentDefinition\x122\n" +
	"\x04kind\x18\x01 \x01(\tB\x1e\xbaH\x1b\xc8\x01\x01r\x16\x10\x012\x12^[a-z][a-z0-9_-]*$R\x04kind\x12$\n" +
	"\x05paths\x18\x02 \x03(\tB\x0e\xbaH\v\x92\x01\b\b\x01\"\x04r\x02\x10\x01R\x05paths\x12+\n" +
	"\vparams_path\x18\x03 \x01(\tB\n" +
	"\xbaH\a\xc8\x01\x01r\x02\x10\x01R\n" +
	"paramsPathB\x85\x01\n" +
	"\vcom.veil.v1B\vConfigProtoP\x01Z,github.com/vercel/veil/api/go/veil/v1;veilv1\xa2\x02\x03VXX\xaa\x02\aVeil.V1\xca\x02\aVeil\\V1\xe2\x02\x13Veil\\V1\\GPBMetadata\xea\x02\bVeil::V1b\x06proto3"

var (
	file_veil_v1_config_proto_rawDescOnce sync.Once
	file_veil_v1_config_proto_rawDescData []byte
)

func file_veil_v1_config_proto_rawDescGZIP() []byte {
	file_veil_v1_config_proto_rawDescOnce.Do(func() {
		file_veil_v1_config_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_veil_v1_config_proto_rawDesc), len(file_veil_v1_config_proto_rawDesc)))
	})
	return file_veil_v1_config_proto_rawDescData
}

var file_veil_v1_config_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_veil_v1_config_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_veil_v1_config_proto_goTypes = []any{
	(VariableType_Enum)(0),       // 0: veil.v1.VariableType.Enum
	(*VeilConfigDefinition)(nil), // 1: veil.v1.VeilConfigDefinition
	(*ResourceDiscovery)(nil),    // 2: veil.v1.ResourceDiscovery
	(*VariableType)(nil),         // 3: veil.v1.VariableType
	(*Variable)(nil),             // 4: veil.v1.Variable
	(*KindDefinition)(nil),       // 5: veil.v1.KindDefinition
	(*HooksDefinition)(nil),      // 6: veil.v1.HooksDefinition
	(*RenderHookDefinition)(nil), // 7: veil.v1.RenderHookDefinition
	(*HookAccess)(nil),           // 8: veil.v1.HookAccess
	(*EnvAccess)(nil),            // 9: veil.v1.EnvAccess
	(*DependentDefinition)(nil),  // 10: veil.v1.DependentDefinition
	nil,                          // 11: veil.v1.VeilConfigDefinition.VariablesEntry
	nil,                          // 12: veil.v1.VeilConfigDefinition.RegistriesEntry
	(*structpb.Value)(nil),       // 13: google.protobuf.Value
}
var file_veil_v1_config_proto_depIdxs = []int32{
	11, // 0: veil.v1.VeilConfigDefinition.variables:type_name -> veil.v1.VeilConfigDefinition.VariablesEntry
	12, // 1: veil.v1.VeilConfigDefinition.registries:type_name -> veil.v1.VeilConfigDefinition.RegistriesEntry
	2,  // 2: veil.v1.VeilConfigDefinition.resource_discovery:type_name -> veil.v1.ResourceDiscovery
	0,  // 3: veil.v1.Variable.type:type_name -> veil.v1.VariableType.Enum
	13, // 4: veil.v1.Variable.default:type_name -> google.protobuf.Value
	13, // 5: veil.v1.Variable.enum:type_name -> google.protobuf.Value
	6,  // 6: veil.v1.KindDefinition.hooks:type_name -> veil.v1.HooksDefinition
	7,  // 7: veil.v1.HooksDefinition.render:type_name -> veil.v1.RenderHookDefinition
	10, // 8: veil.v1.HooksDefinition.dependents:type_name -> veil.v1.DependentDefinition
	8,  // 9: veil.v1.RenderHookDefinition.access:type_name -> veil.v1.HookAccess
	9,  // 10: veil.v1.HookAccess.env:type_name -> veil.v1.EnvAccess
	4,  // 11: veil.v1.VeilConfigDefinition.VariablesEntry.value:type_name -> veil.v1.Variable
	12, // [12:12] is the sub-list for method output_type
	12, // [12:12] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_veil_v1_config_proto_init() }
func file_veil_v1_config_proto_init() {
	if File_veil_v1_config_proto != nil {
		return
	}
	file_veil_v1_config_proto_msgTypes[3].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_veil_v1_config_proto_rawDesc), len(file_veil_v1_config_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_veil_v1_config_proto_goTypes,
		DependencyIndexes: file_veil_v1_config_proto_depIdxs,
		EnumInfos:         file_veil_v1_config_proto_enumTypes,
		MessageInfos:      file_veil_v1_config_proto_msgTypes,
	}.Build()
	File_veil_v1_config_proto = out.File
	file_veil_v1_config_proto_goTypes = nil
	file_veil_v1_config_proto_depIdxs = nil
}
