// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: veil/v1/registry.proto

package veilv1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Kind is the compiled output of `veil build` for a single kind. It bundles
// every source file's contents and every hook's minified code into a
// single document, so rendering does not need access to the original
// filesystem. Compare with KindDefinition (config.proto), which is the
// hand-authored source-side shape that this is compiled from.
type Kind struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Name of the kind (matches KindDefinition.name). Same naming rules
	// — lowercase letter start, then `[a-z0-9_-]`.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Deprecated: use `files`, whose entries carry the same contents and
	// schema plus a `render` flag. Still written by `veil build` — every
	// file with render=true is mirrored here — so a registry built by a
	// newer veil stays readable by an older one. A reader that understands
	// `files` should ignore this.
	//
	// Deprecated: Marked as deprecated in veil/v1/registry.proto.
	Sources []*Source `protobuf:"bytes,2,rep,name=sources,proto3" json:"sources,omitempty"`
	// Files that make up the kind, each carrying its own contents, the
	// schema it validates against when declared, and whether it seeds the
	// rendered output. Supersedes `sources`: a kind may declare either or
	// both, and the loader folds `sources` in as files with render=true.
	Files []*File `protobuf:"bytes,7,rep,name=files,proto3" json:"files,omitempty"`
	// Compiled hooks grouped by lifecycle point — render hooks plus the
	// per-consumer dependent block. Mirrors KindDefinition.hooks.
	Hooks *Hooks `protobuf:"bytes,3,opt,name=hooks,proto3" json:"hooks,omitempty"`
	// Input variable declarations copied from veil.json. Consumers resolve
	// values from --var flags, VEIL_VAR_* env vars, or the declared default.
	Variables map[string]*Variable `protobuf:"bytes,4,rep,name=variables,proto3" json:"variables,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Whether every dependency of a resource of this kind forwards to
	// that resource's consumers, copied from
	// KindDefinition.forward_dependencies. Read at resolve time together
	// with each edge's own `forward` flag — an edge forwards when either
	// says so.
	ForwardDependencies bool `protobuf:"varint,6,opt,name=forward_dependencies,json=forwardDependencies,proto3" json:"forward_dependencies,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *Kind) Reset() {
	*x = Kind{}
	mi := &file_veil_v1_registry_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Kind) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Kind) ProtoMessage() {}

func (x *Kind) ProtoReflect() protoreflect.Message {
	mi := &file_veil_v1_registry_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Kind.ProtoReflect.Descriptor instead.
func (*Kind) Descriptor() ([]byte, []int) {
	return file_veil_v1_registry_proto_rawDescGZIP(), []int{0}
}

func (x *Kind) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// Deprecated: Marked as deprecated in veil/v1/registry.proto.
func (x *Kind) GetSources() []*Source {
	if x != nil {
		return x.Sources
	}
	return nil
}

func (x *Kind) GetFiles() []*File {
	if x != nil {
		return x.Files
	}
	return nil
}

func (x *Kind) GetHooks() *Hooks {
	if x != nil {
		return x.Hooks
	}
	return nil
}

func (x *Kind) GetVariables() map[string]*Variable {
	if x != nil {
		return x.Variables
	}
	return nil
}

func (x *Kind) GetForwardDependencies() bool {
	if x != nil {
		return x.ForwardDependencies
	}
	return false
}

// Source is one compiled source file: where it lives in the kind, what
// it contains, and the schema it is checked against. Everything a
// consumer needs to read and validate the file is inlined here, so
// render never reaches back to the kind directory.
type Source struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Path relative to the kind directory (e.g. "sources/app.json"). Also
	// the source's identity through the render pipeline — hooks may remap
	// where a file is written without changing this.
	Path string `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	// Raw file contents. May be empty: an empty source file is valid.
	Contents string `protobuf:"bytes,2,opt,name=contents,proto3" json:"contents,omitempty"`
	// Inlined JSON Schema for this source, as raw JSON text — like
	// DependentHook.params_schema, so validation needs no filesystem
	// access to the kind directory. Unset when the source declared no
	// schema, in which case its contents are never schema-checked.
	Schema        *string `protobuf:"bytes,3,opt,name=schema,proto3,oneof" json:"schema,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Source) Reset() {
	*x = Source{}
	mi := &file_veil_v1_registry_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Source) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Source) ProtoMessage() {}

func (x *Source) ProtoReflect() protoreflect.Message {
	mi := &file_veil_v1_registry_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Source.ProtoReflect.Descriptor instead.
func (*Source) Descriptor() ([]byte, []int) {
	return file_veil_v1_registry_proto_rawDescGZIP(), []int{1}
}

func (x *Source) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *Source) GetContents() string {
	if x != nil {
		return x.Contents
	}
	return ""
}

func (x *Source) GetSchema() string {
	if x != nil && x.Schema != nil {
		return *x.Schema
	}
	return ""
}

// File is one compiled file belonging to a kind: where it lives, what it
// contains, the schema it is checked against, and whether it seeds the
// rendered output. Everything a consumer needs to read and validate the
// file is inlined here, so render never reaches back to the kind
// directory.
//
// Supersedes Source, which it matches field for field apart from
// `render`. A kind's `sources` load as files with render=true.
type File struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Path relative to the kind directory (e.g. "files/app.json"). Also
	// the file's identity through the render pipeline — hooks may remap
	// where a file is written without changing this.
	Path string `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	// Raw file contents. May be empty: an empty file is valid.
	Contents string `protobuf:"bytes,2,opt,name=contents,proto3" json:"contents,omitempty"`
	// Inlined JSON Schema for this file, as raw JSON text — like
	// DependentHook.params_schema, so validation needs no filesystem
	// access to the kind directory. Unset when the file declared no
	// schema, in which case its contents are never schema-checked.
	Schema *string `protobuf:"bytes,3,opt,name=schema,proto3,oneof" json:"schema,omitempty"`
	// Whether this file seeds the rendered resource. True and it starts
	// the render bundle and is written to the output directory; false and
	// it is an asset the kind ships for its hooks to read, present in the
	// hook FS but never written. Files folded in from `sources` are
	// always true.
	Render        bool `protobuf:"varint,4,opt,name=render,proto3" json:"render,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *File) Reset() {
	*x = File{}
	mi := &file_veil_v1_registry_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *File) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*File) ProtoMessage() {}

func (x *File) ProtoReflect() protoreflect.Message {
	mi := &file_veil_v1_registry_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use File.ProtoReflect.Descriptor instead.
func (*File) Descriptor() ([]byte, []int) {
	return file_veil_v1_registry_proto_rawDescGZIP(), []int{2}
}

func (x *File) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *File) GetContents() string {
	if x != nil {
		return x.Contents
	}
	return ""
}

func (x *File) GetSchema() string {
	if x != nil && x.Schema != nil {
		return *x.Schema
	}
	return ""
}

func (x *File) GetRender() bool {
	if x != nil {
		return x.Render
	}
	return false
}

// Hooks mirrors KindDefinition.hooks but holds compiled/bundled hook
// entries rather than paths.
type Hooks struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Compiled hooks that run during `veil render`, in declaration order.
	Render []*Hook `protobuf:"bytes,1,rep,name=render,proto3" json:"render,omitempty"`
	// Compiled per-consumer dependent entries (one per consumer kind that
	// may depend on this resource). Carries bundled hook code plus the
	// inlined params JSON Schema so render does not need access to the
	// original kind directory.
	Dependents []*DependentHook `protobuf:"bytes,2,rep,name=dependents,proto3" json:"dependents,omitempty"`
	// Compiled validation hooks that run after every other lifecycle
	// point has completed. Bundle / ctx mutations from these hooks are
	// discarded; only the returned `ValidationIssue` entries (or thrown
	// errors) are observable. Mirrors HooksDefinition.validate.
	Validate []*Hook `protobuf:"bytes,3,rep,name=validate,proto3" json:"validate,omitempty"`
	// Compiled post-render hooks. Run after resource-level render hooks
	// and before validate; same RenderHook(ctx, fs) contract as
	// Hooks.render but used for the kind's final normalization /
	// formatting pass once resource customizations have applied.
	// Mirrors HooksDefinition.post_render.
	PostRender    []*Hook `protobuf:"bytes,4,rep,name=post_render,json=postRender,proto3" json:"post_render,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Hooks) Reset() {
	*x = Hooks{}
	mi := &file_veil_v1_registry_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Hooks) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Hooks) ProtoMessage() {}

func (x *Hooks) ProtoReflect() protoreflect.Message {
	mi := &file_veil_v1_registry_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Hooks.ProtoReflect.Descriptor instead.
func (*Hooks) Descriptor() ([]byte, []int) {
	return file_veil_v1_registry_proto_rawDescGZIP(), []int{3}
}

func (x *Hooks) GetRender() []*Hook {
	if x != nil {
		return x.Render
	}
	return nil
}

func (x *Hooks) GetDependents() []*DependentHook {
	if x != nil {
		return x.Dependents
	}
	return nil
}

func (x *Hooks) GetValidate() []*Hook {
	if x != nil {
		return x.Validate
	}
	return nil
}

func (x *Hooks) GetPostRender() []*Hook {
	if x != nil {
		return x.PostRender
	}
	return nil
}

// Registry is the top-level index written to <out>/registry.json by
// `veil build`. It maps kind name → entry describing how to find that kind's
// compiled artifacts. Consumers (e.g. `veil render`) read this to discover
// which kinds are available in a build artifact.
type Registry struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Kind name → entry pointing at the compiled kind document and its schema.
	// All paths are resolved against the registry.json's own directory.
	Kinds         map[string]*RegistryEntry `protobuf:"bytes,1,rep,name=kinds,proto3" json:"kinds,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Registry) Reset() {
	*x = Registry{}
	mi := &file_veil_v1_registry_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Registry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Registry) ProtoMessage() {}

func (x *Registry) ProtoReflect() protoreflect.Message {
	mi := &file_veil_v1_registry_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Registry.ProtoReflect.Descriptor instead.
func (*Registry) Descriptor() ([]byte, []int) {
	return file_veil_v1_registry_proto_rawDescGZIP(), []int{4}
}

func (x *Registry) GetKinds() map[string]*RegistryEntry {
	if x != nil {
		return x.Kinds
	}
	return nil
}

// RegistryEntry describes a single kind in a Registry.
type RegistryEntry struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Name of the kind (matches the map key and Kind.name).
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Relative path to the compiled kind.json (e.g. "./worker/kind.json").
	Path string `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	// Relative path to the kind's composite resource schema
	// (e.g. "./worker/kind.schema.json").
	Schema        string `protobuf:"bytes,3,opt,name=schema,proto3" json:"schema,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegistryEntry) Reset() {
	*x = RegistryEntry{}
	mi := &file_veil_v1_registry_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegistryEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegistryEntry) ProtoMessage() {}

func (x *RegistryEntry) ProtoReflect() protoreflect.Message {
	mi := &file_veil_v1_registry_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegistryEntry.ProtoReflect.Descriptor instead.
func (*RegistryEntry) Descriptor() ([]byte, []int) {
	return file_veil_v1_registry_proto_rawDescGZIP(), []int{5}
}

func (x *RegistryEntry) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RegistryEntry) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *RegistryEntry) GetSchema() string {
	if x != nil {
		return x.Schema
	}
	return ""
}

// Hook is a single hook bundled and minified from its TS/JS source,
// with all of its imports resolved and inlined. Used for both render-
// lifecycle entries (Hooks.render) and dependent-lifecycle entries
// (DependentHook.hooks); the shape is the same in either context.
type Hook struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Relative path from the kind directory (e.g. "hooks/hello-world.ts").
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Minified JavaScript bundle, ES module format.
	Content string `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	// Host resources this hook is permitted to reach (carried forward
	// from the kind.json hook entry). The render runner pre-flights each
	// declared resource and exposes only what's listed to the hook.
	Access        *HookAccess `protobuf:"bytes,3,opt,name=access,proto3" json:"access,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Hook) Reset() {
	*x = Hook{}
	mi := &file_veil_v1_registry_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Hook) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Hook) ProtoMessage() {}

func (x *Hook) ProtoReflect() protoreflect.Message {
	mi := &file_veil_v1_registry_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Hook.ProtoReflect.Descriptor instead.
func (*Hook) Descriptor() ([]byte, []int) {
	return file_veil_v1_registry_proto_rawDescGZIP(), []int{6}
}

func (x *Hook) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Hook) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *Hook) GetAccess() *HookAccess {
	if x != nil {
		return x.Access
	}
	return nil
}

// DependentHook is the compiled form of a KindDefinition.dependents
// entry: each hook source is bundled, and the params JSON Schema is
// embedded inline so rendering does not need access to the original
// kind directory.
type DependentHook struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The consumer kind that may depend on this resource (matches
	// DependentDefinition.kind).
	Kind string `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty"`
	// Compiled, bundled dependent hooks in declaration order.
	Hooks []*Hook `protobuf:"bytes,2,rep,name=hooks,proto3" json:"hooks,omitempty"`
	// Inlined contents of the params JSON Schema (raw JSON text).
	ParamsSchema  string `protobuf:"bytes,3,opt,name=params_schema,json=paramsSchema,proto3" json:"params_schema,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DependentHook) Reset() {
	*x = DependentHook{}
	mi := &file_veil_v1_registry_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DependentHook) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DependentHook) ProtoMessage() {}

func (x *DependentHook) ProtoReflect() protoreflect.Message {
	mi := &file_veil_v1_registry_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DependentHook.ProtoReflect.Descriptor instead.
func (*DependentHook) Descriptor() ([]byte, []int) {
	return file_veil_v1_registry_proto_rawDescGZIP(), []int{7}
}

func (x *DependentHook) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *DependentHook) GetHooks() []*Hook {
	if x != nil {
		return x.Hooks
	}
	return nil
}

func (x *DependentHook) GetParamsSchema() string {
	if x != nil {
		return x.ParamsSchema
	}
	return ""
}

var File_veil_v1_registry_proto protoreflect.FileDescriptor

const file_veil_v1_registry_proto_rawDesc = "" +
	"\n" +
	"\x16veil/v1/registry.proto\x12\aveil.v1\x1a\x1bbuf/validate/validate.proto\x1a\x14veil/v1/config.proto\"\x9a\x03\n" +
	"\x04Kind\x122\n" +
	"\x04name\x18\x01 \x01(\tB\x1e\xbaH\x1b\xc8\x01\x01r\x16\x10\x012\x12^[a-z][a-z0-9_-]*$R\x04name\x12-\n" +
	"\asources\x18\x02 \x03(\v2\x0f.veil.v1.SourceB\x02\x18\x01R\asources\x12#\n" +
	"\x05files\x18\a \x03(\v2\r.veil.v1.FileR\x05files\x12$\n" +
	"\x05hooks\x18\x03 \x01(\v2\x0e.veil.v1.HooksR\x05hooks\x12`\n" +
	"\tvariables\x18\x04 \x03(\v2\x1c.veil.v1.Kind.VariablesEntryB$\xbaH!\x9a\x01\x1e\"\x1cr\x1a2\x18^[a-zA-Z_][a-zA-Z0-9_]*$R\tvariables\x121\n" +
	"\x14forward_dependencies\x18\x06 \x01(\bR\x13forwardDependencies\x1aO\n" +
	"\x0eVariablesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12'\n" +
	"\x05value\x18\x02 \x01(\v2\x11.veil.v1.VariableR\x05value:\x028\x01\"l\n" +
	"\x06Source\x12\x1e\n" +
	"\x04path\x18\x01 \x01(\tB\n" +
	"\xbaH\a\xc8\x01\x01r\x02\x10\x01R\x04path\x12\x1a\n" +
	"\bcontents\x18\x02 \x01(\tR\bcontents\x12\x1b\n" +
	"\x06schema\x18\x03 \x01(\tH\x00R\x06schema\x88\x01\x01B\t\n" +
	"\a_schema\"\x82\x01\n" +
	"\x04File\x12\x1e\n" +
	"\x04path\x18\x01 \x01(\tB\n" +
	"\xbaH\a\xc8\x01\x01r\x02\x10\x01R\x04path\x12\x1a\n" +
	"\bcontents\x18\x02 \x01(\tR\bcontents\x12\x1b\n" +
	"\x06schema\x18\x03 \x01(\tH\x00R\x06schema\x88\x01\x01\x12\x16\n" +
	"\x06render\x18\x04 \x01(\bR\x06renderB\t\n" +
	"\a_schema\"\xc1\x01\n" +
	"\x05Hooks\x12%\n" +
	"\x06render\x18\x01 \x03(\v2\r.veil.v1.HookR\x06render\x126\n" +
	"\n" +
	"dependents\x18\x02 \x03(\v2\x16.veil.v1.DependentHookR\n" +
	"dependents\x12)\n" +
	"\bvalidate\x18\x03 \x03(\v2\r.veil.v1.HookR\bvalidate\x12.\n" +
	"\vpost_render\x18\x04 \x03(\v2\r.veil.v1.HookR\n" +
	"postRender\"\xb0\x01\n" +
	"\bRegistry\x12R\n" +
	"\x05kinds\x18\x01 \x03(\v2\x1c.veil.v1.Registry.KindsEntryB\x1e\xbaH\x1b\x9a\x01\x18\"\x16r\x142\x12^[a-z][a-z0-9_-]*$R\x05kinds\x1aP\n" +
	"\n" +
	"KindsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12,\n" +
	"\x05value\x18\x02 \x01(\v2\x16.veil.v1.RegistryEntryR\x05value:\x028\x01\"\x87\x01\n" +
	"\rRegistryEntry\x122\n" +
	"\x04name\x18\x01 \x01(\tB\x1e\xbaH\x1b\xc8\x01\x01r\x16\x10\x012\x12^[a-z][a-z0-9_-]*$R\x04name\x12\x1e\n" +
	"\x04path\x18\x02 \x01(\tB\n" +
	"\xbaH\a\xc8\x01\x01r\x02\x10\x01R\x04path\x12\"\n" +
	"\x06schema\x18\x03 \x01(\tB\n" +
	"\xbaH\a\xc8\x01\x01r\x02\x10\x01R\x06schema\"y\n" +
	"\x04Hook\x12\x1e\n" +
	"\x04name\x18\x01 \x01(\tB\n" +
	"\xbaH\a\xc8\x01\x01r\x02\x10\x01R\x04name\x12$\n" +
	"\acontent\x18\x02 \x01(\tB\n" +
	"\xbaH\a\xc8\x01\x01r\x02\x10\x01R\acontent\x12+\n" +
	"\x06access\x18\x03 \x01(\v2\x13.veil.v1.HookAccessR\x06access\"\xa3\x01\n" +
	"\rDependentHook\x122\n" +
	"\x04kind\x18\x01 \x01(\tB\x1e\xbaH\x1b\xc8\x01\x01r\x16\x10\x012\x12^[a-z][a-z0-9_-]*$R\x04kind\x12-\n" +
	"\x05hooks\x18\x02 \x03(\v2\r.veil.v1.HookB\b\xbaH\x05\x92\x01\x02\b\x01R\x05hooks\x12/\n" +
	"\rparams_schema\x18\x03 \x01(\tB\n" +
	"\xbaH\a\xc8\x01\x01r\x02\x10\x01R\fparamsSchemaB\x87\x01\n" +
	"\vcom.veil.v1B\rRegistryProtoP\x01Z,github.com/vercel/veil/api/go/veil/v1;veilv1\xa2\x02\x03VXX\xaa\x02\aVeil.V1\xca\x02\aVeil\\V1\xe2\x02\x13Veil\\V1\\GPBMetadata\xea\x02\bVeil::V1b\x06proto3"

var (
	file_veil_v1_registry_proto_rawDescOnce sync.Once
	file_veil_v1_registry_proto_rawDescData []byte
)

func file_veil_v1_registry_proto_rawDescGZIP() []byte {
	file_veil_v1_registry_proto_rawDescOnce.Do(func() {
		file_veil_v1_registry_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_veil_v1_registry_proto_rawDesc), len(file_veil_v1_registry_proto_rawDesc)))
	})
	return file_veil_v1_registry_proto_rawDescData
}

var file_veil_v1_registry_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_veil_v1_registry_proto_goTypes = []any{
	(*Kind)(nil),          // 0: veil.v1.Kind
	(*Source)(nil),        // 1: veil.v1.Source
	(*File)(nil),          // 2: veil.v1.File
	(*Hooks)(nil),         // 3: veil.v1.Hooks
	(*Registry)(nil),      // 4: veil.v1.Registry
	(*RegistryEntry)(nil), // 5: veil.v1.RegistryEntry
	(*Hook)(nil),          // 6: veil.v1.Hook
	(*DependentHook)(nil), // 7: veil.v1.DependentHook
	nil,                   // 8: veil.v1.Kind.VariablesEntry
	nil,                   // 9: veil.v1.Registry.KindsEntry
	(*HookAccess)(nil),    // 10: veil.v1.HookAccess
	(*Variable)(nil),      // 11: veil.v1.Variable
}
var file_veil_v1_registry_proto_depIdxs = []int32{
	1,  // 0: veil.v1.Kind.sources:type_name -> veil.v1.Source
	2,  // 1: veil.v1.Kind.files:type_name -> veil.v1.File
	3,  // 2: veil.v1.Kind.hooks:type_name -> veil.v1.Hooks
	8,  // 3: veil.v1.Kind.variables:type_name -> veil.v1.Kind.VariablesEntry
	6,  // 4: veil.v1.Hooks.render:type_name -> veil.v1.Hook
	7,  // 5: veil.v1.Hooks.dependents:type_name -> veil.v1.DependentHook
	6,  // 6: veil.v1.Hooks.validate:type_name -> veil.v1.Hook
	6,  // 7: veil.v1.Hooks.post_render:type_name -> veil.v1.Hook
	9,  // 8: veil.v1.Registry.kinds:type_name -> veil.v1.Registry.KindsEntry
	10, // 9: veil.v1.Hook.access:type_name -> veil.v1.HookAccess
	6,  // 10: veil.v1.DependentHook.hooks:type_name -> veil.v1.Hook
	11, // 11: veil.v1.Kind.VariablesEntry.value:type_name -> veil.v1.Variable
	5,  // 12: veil.v1.Registry.KindsEntry.value:type_name -> veil.v1.RegistryEntry
	13, // [13:13] is the sub-list for method output_type
	13, // [13:13] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_veil_v1_registry_proto_init() }
func file_veil_v1_registry_proto_init() {
	if File_veil_v1_registry_proto != nil {
		return
	}
	file_veil_v1_config_proto_init()
	file_veil_v1_registry_proto_msgTypes[1].OneofWrappers = []any{}
	file_veil_v1_registry_proto_msgTypes[2].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_veil_v1_registry_proto_rawDesc), len(file_veil_v1_registry_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_veil_v1_registry_proto_goTypes,
		DependencyIndexes: file_veil_v1_registry_proto_depIdxs,
		MessageInfos:      file_veil_v1_registry_proto_msgTypes,
	}.Build()
	File_veil_v1_registry_proto = out.File
	file_veil_v1_registry_proto_goTypes = nil
	file_veil_v1_registry_proto_depIdxs = nil
}
