// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: veil/v1/resource.proto

package veilv1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Resource is a consumer's instantiation of a kind.
type Resource struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Standard metadata common to all resources.
	Metadata *Metadata `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	// Resource-specific data validated against the kind's schema.
	Spec          *structpb.Struct `protobuf:"bytes,2,opt,name=spec,proto3" json:"spec,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Resource) Reset() {
	*x = Resource{}
	mi := &file_veil_v1_resource_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Resource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Resource) ProtoMessage() {}

func (x *Resource) ProtoReflect() protoreflect.Message {
	mi := &file_veil_v1_resource_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Resource.ProtoReflect.Descriptor instead.
func (*Resource) Descriptor() ([]byte, []int) {
	return file_veil_v1_resource_proto_rawDescGZIP(), []int{0}
}

func (x *Resource) GetMetadata() *Metadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *Resource) GetSpec() *structpb.Struct {
	if x != nil {
		return x.Spec
	}
	return nil
}

// Metadata contains fields common to every resource.
type Metadata struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The name of this resource.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Conditional overlays applied based on CEL expressions.
	Overlays []*Overlay `protobuf:"bytes,2,rep,name=overlays,proto3" json:"overlays,omitempty"`
	// Source files that have been ejected for local override.
	Overrides []*Override `protobuf:"bytes,3,rep,name=overrides,proto3" json:"overrides,omitempty"`
	// The name of the kind this resource instantiates. Must match a kind
	// present in one of the loaded registries.
	Kind          string `protobuf:"bytes,4,opt,name=kind,proto3" json:"kind,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Metadata) Reset() {
	*x = Metadata{}
	mi := &file_veil_v1_resource_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Metadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Metadata) ProtoMessage() {}

func (x *Metadata) ProtoReflect() protoreflect.Message {
	mi := &file_veil_v1_resource_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Metadata.ProtoReflect.Descriptor instead.
func (*Metadata) Descriptor() ([]byte, []int) {
	return file_veil_v1_resource_proto_rawDescGZIP(), []int{1}
}

func (x *Metadata) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Metadata) GetOverlays() []*Overlay {
	if x != nil {
		return x.Overlays
	}
	return nil
}

func (x *Metadata) GetOverrides() []*Override {
	if x != nil {
		return x.Overrides
	}
	return nil
}

func (x *Metadata) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

// Overlay is a conditional data merge applied before transforms.
type Overlay struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// CEL expression evaluated against the render context.
	Match string `protobuf:"bytes,1,opt,name=match,proto3" json:"match,omitempty"`
	// Path to the overlay file. Resolved relative to the resource file
	// that declares this overlay, or used as-is when absolute.
	File          string `protobuf:"bytes,2,opt,name=file,proto3" json:"file,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Overlay) Reset() {
	*x = Overlay{}
	mi := &file_veil_v1_resource_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Overlay) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Overlay) ProtoMessage() {}

func (x *Overlay) ProtoReflect() protoreflect.Message {
	mi := &file_veil_v1_resource_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Overlay.ProtoReflect.Descriptor instead.
func (*Overlay) Descriptor() ([]byte, []int) {
	return file_veil_v1_resource_proto_rawDescGZIP(), []int{2}
}

func (x *Overlay) GetMatch() string {
	if x != nil {
		return x.Match
	}
	return ""
}

func (x *Overlay) GetFile() string {
	if x != nil {
		return x.File
	}
	return ""
}

// Override maps a kind source file to a local replacement.
type Override struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Path of the source file in the kind being replaced.
	Source string `protobuf:"bytes,1,opt,name=source,proto3" json:"source,omitempty"`
	// Local path to the override file.
	Path          string `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Override) Reset() {
	*x = Override{}
	mi := &file_veil_v1_resource_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Override) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Override) ProtoMessage() {}

func (x *Override) ProtoReflect() protoreflect.Message {
	mi := &file_veil_v1_resource_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Override.ProtoReflect.Descriptor instead.
func (*Override) Descriptor() ([]byte, []int) {
	return file_veil_v1_resource_proto_rawDescGZIP(), []int{3}
}

func (x *Override) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *Override) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

var File_veil_v1_resource_proto protoreflect.FileDescriptor

const file_veil_v1_resource_proto_rawDesc = "" +
	"\n" +
	"\x16veil/v1/resource.proto\x12\aveil.v1\x1a\x1bbuf/validate/validate.proto\x1a\x1cgoogle/protobuf/struct.proto\"n\n" +
	"\bResource\x125\n" +
	"\bmetadata\x18\x01 \x01(\v2\x11.veil.v1.MetadataB\x06\xbaH\x03\xc8\x01\x01R\bmetadata\x12+\n" +
	"\x04spec\x18\x02 \x01(\v2\x17.google.protobuf.StructR\x04spec\"\xa9\x01\n" +
	"\bMetadata\x12\x1e\n" +
	"\x04name\x18\x01 \x01(\tB\n" +
	"\xbaH\a\xc8\x01\x01r\x02\x10\x01R\x04name\x12,\n" +
	"\boverlays\x18\x02 \x03(\v2\x10.veil.v1.OverlayR\boverlays\x12/\n" +
	"\toverrides\x18\x03 \x03(\v2\x11.veil.v1.OverrideR\toverrides\x12\x1e\n" +
	"\x04kind\x18\x04 \x01(\tB\n" +
	"\xbaH\a\xc8\x01\x01r\x02\x10\x01R\x04kind\"K\n" +
	"\aOverlay\x12 \n" +
	"\x05match\x18\x01 \x01(\tB\n" +
	"\xbaH\a\xc8\x01\x01r\x02\x10\x01R\x05match\x12\x1e\n" +
	"\x04file\x18\x02 \x01(\tB\n" +
	"\xbaH\a\xc8\x01\x01r\x02\x10\x01R\x04file\"N\n" +
	"\bOverride\x12\"\n" +
	"\x06source\x18\x01 \x01(\tB\n" +
	"\xbaH\a\xc8\x01\x01r\x02\x10\x01R\x06source\x12\x1e\n" +
	"\x04path\x18\x02 \x01(\tB\n" +
	"\xbaH\a\xc8\x01\x01r\x02\x10\x01R\x04pathB\x87\x01\n" +
	"\vcom.veil.v1B\rResourceProtoP\x01Z,github.com/vercel/veil/api/go/veil/v1;veilv1\xa2\x02\x03VXX\xaa\x02\aVeil.V1\xca\x02\aVeil\\V1\xe2\x02\x13Veil\\V1\\GPBMetadata\xea\x02\bVeil::V1b\x06proto3"

var (
	file_veil_v1_resource_proto_rawDescOnce sync.Once
	file_veil_v1_resource_proto_rawDescData []byte
)

func file_veil_v1_resource_proto_rawDescGZIP() []byte {
	file_veil_v1_resource_proto_rawDescOnce.Do(func() {
		file_veil_v1_resource_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_veil_v1_resource_proto_rawDesc), len(file_veil_v1_resource_proto_rawDesc)))
	})
	return file_veil_v1_resource_proto_rawDescData
}

var file_veil_v1_resource_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_veil_v1_resource_proto_goTypes = []any{
	(*Resource)(nil),        // 0: veil.v1.Resource
	(*Metadata)(nil),        // 1: veil.v1.Metadata
	(*Overlay)(nil),         // 2: veil.v1.Overlay
	(*Override)(nil),        // 3: veil.v1.Override
	(*structpb.Struct)(nil), // 4: google.protobuf.Struct
}
var file_veil_v1_resource_proto_depIdxs = []int32{
	1, // 0: veil.v1.Resource.metadata:type_name -> veil.v1.Metadata
	4, // 1: veil.v1.Resource.spec:type_name -> google.protobuf.Struct
	2, // 2: veil.v1.Metadata.overlays:type_name -> veil.v1.Overlay
	3, // 3: veil.v1.Metadata.overrides:type_name -> veil.v1.Override
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_veil_v1_resource_proto_init() }
func file_veil_v1_resource_proto_init() {
	if File_veil_v1_resource_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_veil_v1_resource_proto_rawDesc), len(file_veil_v1_resource_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_veil_v1_resource_proto_goTypes,
		DependencyIndexes: file_veil_v1_resource_proto_depIdxs,
		MessageInfos:      file_veil_v1_resource_proto_msgTypes,
	}.Build()
	File_veil_v1_resource_proto = out.File
	file_veil_v1_resource_proto_goTypes = nil
	file_veil_v1_resource_proto_depIdxs = nil
}
