// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: veil/v1/resource.proto

package veilv1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Enum of legal file types. The zero value (`definition`) is the
// historical default — files written before file_type existed are
// treated exactly as they always have been.
//
// buf:lint:ignore ENUM_VALUE_UPPER_SNAKE_CASE
// buf:lint:ignore ENUM_VALUE_PREFIX
// buf:lint:ignore ENUM_ZERO_VALUE_SUFFIX
type FileType_Enum int32

const (
	// buf:lint:ignore ENUM_VALUE_UPPER_SNAKE_CASE
	// buf:lint:ignore ENUM_VALUE_PREFIX
	// buf:lint:ignore ENUM_ZERO_VALUE_SUFFIX
	FileType_definition FileType_Enum = 0
	// buf:lint:ignore ENUM_VALUE_UPPER_SNAKE_CASE
	// buf:lint:ignore ENUM_VALUE_PREFIX
	FileType_overlay FileType_Enum = 1
)

// Enum value maps for FileType_Enum.
var (
	FileType_Enum_name = map[int32]string{
		0: "definition",
		1: "overlay",
	}
	FileType_Enum_value = map[string]int32{
		"definition": 0,
		"overlay":    1,
	}
)

func (x FileType_Enum) Enum() *FileType_Enum {
	p := new(FileType_Enum)
	*p = x
	return p
}

func (x FileType_Enum) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FileType_Enum) Descriptor() protoreflect.EnumDescriptor {
	return file_veil_v1_resource_proto_enumTypes[0].Descriptor()
}

func (FileType_Enum) Type() protoreflect.EnumType {
	return &file_veil_v1_resource_proto_enumTypes[0]
}

func (x FileType_Enum) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FileType_Enum.Descriptor instead.
func (FileType_Enum) EnumDescriptor() ([]byte, []int) {
	return file_veil_v1_resource_proto_rawDescGZIP(), []int{3, 0}
}

// Resource is a consumer's instantiation of a kind.
type Resource struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Standard metadata common to all resources.
	Metadata *Metadata `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	// Resource-specific data validated against the kind's schema.
	Spec *structpb.Struct `protobuf:"bytes,2,opt,name=spec,proto3" json:"spec,omitempty"`
	// Other resources this one depends on. Each entry triggers the target
	// kind's `dependent` hook(s) against this resource's bundle during
	// render. See SPEC.md "Dependencies".
	Dependencies  []*Dependency `protobuf:"bytes,3,rep,name=dependencies,proto3" json:"dependencies,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Resource) Reset() {
	*x = Resource{}
	mi := &file_veil_v1_resource_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Resource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Resource) ProtoMessage() {}

func (x *Resource) ProtoReflect() protoreflect.Message {
	mi := &file_veil_v1_resource_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Resource.ProtoReflect.Descriptor instead.
func (*Resource) Descriptor() ([]byte, []int) {
	return file_veil_v1_resource_proto_rawDescGZIP(), []int{0}
}

func (x *Resource) GetMetadata() *Metadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *Resource) GetSpec() *structpb.Struct {
	if x != nil {
		return x.Spec
	}
	return nil
}

func (x *Resource) GetDependencies() []*Dependency {
	if x != nil {
		return x.Dependencies
	}
	return nil
}

// Dependency declares that this resource depends on another resource.
// The depended-on resource (target) authoritatively controls how this
// resource talks to it via the target's `dependent` hooks.
type Dependency struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The kind of the target resource.
	Kind string `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty"`
	// The name of the target resource. The pair (kind, name) must resolve
	// to a resource in the catalog at render time.
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// Arbitrary parameters the target's `dependent` hook receives. The
	// shape is defined by the target kind's matching dependents entry.
	Params        *structpb.Struct `protobuf:"bytes,3,opt,name=params,proto3" json:"params,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Dependency) Reset() {
	*x = Dependency{}
	mi := &file_veil_v1_resource_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Dependency) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Dependency) ProtoMessage() {}

func (x *Dependency) ProtoReflect() protoreflect.Message {
	mi := &file_veil_v1_resource_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Dependency.ProtoReflect.Descriptor instead.
func (*Dependency) Descriptor() ([]byte, []int) {
	return file_veil_v1_resource_proto_rawDescGZIP(), []int{1}
}

func (x *Dependency) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *Dependency) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Dependency) GetParams() *structpb.Struct {
	if x != nil {
		return x.Params
	}
	return nil
}

// Metadata contains fields common to every resource. The presence of
// `file_type` (and its default of `definition`) lets the catalog tell
// authoritative resource files apart from overlay fragments without
// needing to inspect every other field.
type Metadata struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The name of this resource. Required when `file_type` is
	// `definition` (the default); ignored entirely when `file_type` is
	// `overlay` — overlays cannot rename their target resource.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Conditional overlays applied based on per-variable regex matches.
	Overlays []*Overlay `protobuf:"bytes,2,rep,name=overlays,proto3" json:"overlays,omitempty"`
	// Source files that have been ejected for local override.
	Overrides []*Override `protobuf:"bytes,3,rep,name=overrides,proto3" json:"overrides,omitempty"`
	// The name of the kind this resource instantiates. Required when
	// `file_type` is `definition`; ignored when `file_type` is
	// `overlay` — overlays cannot reassign their target's kind.
	Kind string `protobuf:"bytes,4,opt,name=kind,proto3" json:"kind,omitempty"`
	// What kind of file this metadata block belongs to. Defaults to
	// `definition` when omitted (the historical / authoritative
	// resource-file shape). Set to `overlay` on overlay fragments so
	// the catalog walker can skip them without name/kind heuristics.
	FileType      FileType_Enum `protobuf:"varint,5,opt,name=file_type,json=fileType,proto3,enum=veil.v1.FileType_Enum" json:"file_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Metadata) Reset() {
	*x = Metadata{}
	mi := &file_veil_v1_resource_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Metadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Metadata) ProtoMessage() {}

func (x *Metadata) ProtoReflect() protoreflect.Message {
	mi := &file_veil_v1_resource_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Metadata.ProtoReflect.Descriptor instead.
func (*Metadata) Descriptor() ([]byte, []int) {
	return file_veil_v1_resource_proto_rawDescGZIP(), []int{2}
}

func (x *Metadata) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Metadata) GetOverlays() []*Overlay {
	if x != nil {
		return x.Overlays
	}
	return nil
}

func (x *Metadata) GetOverrides() []*Override {
	if x != nil {
		return x.Overrides
	}
	return nil
}

func (x *Metadata) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *Metadata) GetFileType() FileType_Enum {
	if x != nil {
		return x.FileType
	}
	return FileType_definition
}

// FileType is the wrapper message for the Metadata.file_type enum.
// Wrapping it in a message gives the Go-generated identifiers a clean
// nested form (FileType_Enum_*) and lets the JSON wire format use
// lowercase value names ("definition", "overlay").
type FileType struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileType) Reset() {
	*x = FileType{}
	mi := &file_veil_v1_resource_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileType) ProtoMessage() {}

func (x *FileType) ProtoReflect() protoreflect.Message {
	mi := &file_veil_v1_resource_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileType.ProtoReflect.Descriptor instead.
func (*FileType) Descriptor() ([]byte, []int) {
	return file_veil_v1_resource_proto_rawDescGZIP(), []int{3}
}

// Overlay is a conditional data merge applied before transforms. The
// overlay applies when every entry in `if` matches: the resolved
// value of each named variable (stringified) must match the
// corresponding Go regular expression.
type Overlay struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Map of variable name → regex pattern. All entries must match for
	// the overlay to apply. An empty map means "always apply".
	//
	// buf:lint:ignore FIELD_LOWER_SNAKE_CASE
	If map[string]string `protobuf:"bytes,1,rep,name=if,proto3" json:"if,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Path to the overlay file. Resolved relative to the resource file
	// that declares this overlay, or used as-is when absolute.
	File          string `protobuf:"bytes,2,opt,name=file,proto3" json:"file,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Overlay) Reset() {
	*x = Overlay{}
	mi := &file_veil_v1_resource_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Overlay) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Overlay) ProtoMessage() {}

func (x *Overlay) ProtoReflect() protoreflect.Message {
	mi := &file_veil_v1_resource_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Overlay.ProtoReflect.Descriptor instead.
func (*Overlay) Descriptor() ([]byte, []int) {
	return file_veil_v1_resource_proto_rawDescGZIP(), []int{4}
}

func (x *Overlay) GetIf() map[string]string {
	if x != nil {
		return x.If
	}
	return nil
}

func (x *Overlay) GetFile() string {
	if x != nil {
		return x.File
	}
	return ""
}

// Override maps a kind source file to a local replacement.
type Override struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Path of the source file in the kind being replaced.
	Source string `protobuf:"bytes,1,opt,name=source,proto3" json:"source,omitempty"`
	// Local path to the override file. Resolved relative to the
	// resource file that declares this override, or used as-is when
	// absolute.
	Path string `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	// When true, render hooks may still observe and edit this file
	// during the pipeline, but their changes are discarded at write
	// time — the final rendered output is exactly the local override
	// content, byte-for-byte. Use this when the kind's hooks would
	// otherwise stomp on a hand-tuned customization.
	SkipHooks     bool `protobuf:"varint,3,opt,name=skip_hooks,json=skipHooks,proto3" json:"skip_hooks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Override) Reset() {
	*x = Override{}
	mi := &file_veil_v1_resource_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Override) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Override) ProtoMessage() {}

func (x *Override) ProtoReflect() protoreflect.Message {
	mi := &file_veil_v1_resource_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Override.ProtoReflect.Descriptor instead.
func (*Override) Descriptor() ([]byte, []int) {
	return file_veil_v1_resource_proto_rawDescGZIP(), []int{5}
}

func (x *Override) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *Override) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *Override) GetSkipHooks() bool {
	if x != nil {
		return x.SkipHooks
	}
	return false
}

var File_veil_v1_resource_proto protoreflect.FileDescriptor

const file_veil_v1_resource_proto_rawDesc = "" +
	"\n" +
	"\x16veil/v1/resource.proto\x12\aveil.v1\x1a\x1bbuf/validate/validate.proto\x1a\x1cgoogle/protobuf/struct.proto\"\xa7\x01\n" +
	"\bResource\x125\n" +
	"\bmetadata\x18\x01 \x01(\v2\x11.veil.v1.MetadataB\x06\xbaH\x03\xc8\x01\x01R\bmetadata\x12+\n" +
	"\x04spec\x18\x02 \x01(\v2\x17.google.protobuf.StructR\x04spec\x127\n" +
	"\fdependencies\x18\x03 \x03(\v2\x13.veil.v1.DependencyR\fdependencies\"}\n" +
	"\n" +
	"Dependency\x12\x1e\n" +
	"\x04kind\x18\x01 \x01(\tB\n" +
	"\xbaH\a\xc8\x01\x01r\x02\x10\x01R\x04kind\x12\x1e\n" +
	"\x04name\x18\x02 \x01(\tB\n" +
	"\xbaH\a\xc8\x01\x01r\x02\x10\x01R\x04name\x12/\n" +
	"\x06params\x18\x03 \x01(\v2\x17.google.protobuf.StructR\x06params\"\xd0\x01\n" +
	"\bMetadata\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12,\n" +
	"\boverlays\x18\x02 \x03(\v2\x10.veil.v1.OverlayR\boverlays\x12/\n" +
	"\toverrides\x18\x03 \x03(\v2\x11.veil.v1.OverrideR\toverrides\x12\x12\n" +
	"\x04kind\x18\x04 \x01(\tR\x04kind\x12=\n" +
	"\tfile_type\x18\x05 \x01(\x0e2\x16.veil.v1.FileType.EnumB\b\xbaH\x05\x82\x01\x02\x10\x01R\bfileType\"/\n" +
	"\bFileType\"#\n" +
	"\x04Enum\x12\x0e\n" +
	"\n" +
	"definition\x10\x00\x12\v\n" +
	"\aoverlay\x10\x01\"\x8a\x01\n" +
	"\aOverlay\x12(\n" +
	"\x02if\x18\x01 \x03(\v2\x18.veil.v1.Overlay.IfEntryR\x02if\x12\x1e\n" +
	"\x04file\x18\x02 \x01(\tB\n" +
	"\xbaH\a\xc8\x01\x01r\x02\x10\x01R\x04file\x1a5\n" +
	"\aIfEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"m\n" +
	"\bOverride\x12\"\n" +
	"\x06source\x18\x01 \x01(\tB\n" +
	"\xbaH\a\xc8\x01\x01r\x02\x10\x01R\x06source\x12\x1e\n" +
	"\x04path\x18\x02 \x01(\tB\n" +
	"\xbaH\a\xc8\x01\x01r\x02\x10\x01R\x04path\x12\x1d\n" +
	"\n" +
	"skip_hooks\x18\x03 \x01(\bR\tskipHooksB\x87\x01\n" +
	"\vcom.veil.v1B\rResourceProtoP\x01Z,github.com/vercel/veil/api/go/veil/v1;veilv1\xa2\x02\x03VXX\xaa\x02\aVeil.V1\xca\x02\aVeil\\V1\xe2\x02\x13Veil\\V1\\GPBMetadata\xea\x02\bVeil::V1b\x06proto3"

var (
	file_veil_v1_resource_proto_rawDescOnce sync.Once
	file_veil_v1_resource_proto_rawDescData []byte
)

func file_veil_v1_resource_proto_rawDescGZIP() []byte {
	file_veil_v1_resource_proto_rawDescOnce.Do(func() {
		file_veil_v1_resource_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_veil_v1_resource_proto_rawDesc), len(file_veil_v1_resource_proto_rawDesc)))
	})
	return file_veil_v1_resource_proto_rawDescData
}

var file_veil_v1_resource_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_veil_v1_resource_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_veil_v1_resource_proto_goTypes = []any{
	(FileType_Enum)(0),      // 0: veil.v1.FileType.Enum
	(*Resource)(nil),        // 1: veil.v1.Resource
	(*Dependency)(nil),      // 2: veil.v1.Dependency
	(*Metadata)(nil),        // 3: veil.v1.Metadata
	(*FileType)(nil),        // 4: veil.v1.FileType
	(*Overlay)(nil),         // 5: veil.v1.Overlay
	(*Override)(nil),        // 6: veil.v1.Override
	nil,                     // 7: veil.v1.Overlay.IfEntry
	(*structpb.Struct)(nil), // 8: google.protobuf.Struct
}
var file_veil_v1_resource_proto_depIdxs = []int32{
	3, // 0: veil.v1.Resource.metadata:type_name -> veil.v1.Metadata
	8, // 1: veil.v1.Resource.spec:type_name -> google.protobuf.Struct
	2, // 2: veil.v1.Resource.dependencies:type_name -> veil.v1.Dependency
	8, // 3: veil.v1.Dependency.params:type_name -> google.protobuf.Struct
	5, // 4: veil.v1.Metadata.overlays:type_name -> veil.v1.Overlay
	6, // 5: veil.v1.Metadata.overrides:type_name -> veil.v1.Override
	0, // 6: veil.v1.Metadata.file_type:type_name -> veil.v1.FileType.Enum
	7, // 7: veil.v1.Overlay.if:type_name -> veil.v1.Overlay.IfEntry
	8, // [8:8] is the sub-list for method output_type
	8, // [8:8] is the sub-list for method input_type
	8, // [8:8] is the sub-list for extension type_name
	8, // [8:8] is the sub-list for extension extendee
	0, // [0:8] is the sub-list for field type_name
}

func init() { file_veil_v1_resource_proto_init() }
func file_veil_v1_resource_proto_init() {
	if File_veil_v1_resource_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_veil_v1_resource_proto_rawDesc), len(file_veil_v1_resource_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_veil_v1_resource_proto_goTypes,
		DependencyIndexes: file_veil_v1_resource_proto_depIdxs,
		EnumInfos:         file_veil_v1_resource_proto_enumTypes,
		MessageInfos:      file_veil_v1_resource_proto_msgTypes,
	}.Build()
	File_veil_v1_resource_proto = out.File
	file_veil_v1_resource_proto_goTypes = nil
	file_veil_v1_resource_proto_depIdxs = nil
}
