// Generated by veil build — do not edit.

/** An Acme VPC — the network every other resource is placed in. */
export interface VpcSpec {
  availabilityZones: number;
  /** Address range, e.g. 10.0.0.0/16 */
  cidr: string;
}

export interface RegistryVariables {
  /** Which Acme environment is being rendered */
  environment: "staging" | "production";
  /** Cloud region every resource lands in */
  region: string;
}

export interface YamlCodec {
  /** Parse a YAML string into a JS value. Throws on malformed YAML. */
  parse(s: string): unknown;
  /** Serialize a JS value to YAML. Output uses 2-space indent and
   *  alphabetized keys (the gopkg.in/yaml.v3 default for maps). */
  stringify(value: unknown): string;
}

/** One item in a body: an attribute, a nested block, or a comment. */
export type TFItem = TFAttribute | TFBlock | TFComment;

export interface TFAttribute {
  name(): string;
  /** Rename in place, keeping position and expression. Nothing stops a
   *  rename onto a sibling, and two attributes of one name is something
   *  Terraform rejects — checking that is the caller's. */
  setName(name: string): TFAttribute;
  /** The expression as source text, unevaluated: var.region stays
   *  var.region rather than becoming a value. */
  expr(): string;
  /** Replace the expression with raw source text, so the caller decides
   *  between a literal and a reference. */
  setExpr(expr: string): TFAttribute;
  /** Replace it with an encoded value — the same encoding setAttribute
   *  uses. */
  setValue(value: unknown): TFAttribute;
  delete(): boolean;
}

export interface TFComment {
  /** The comment including its marker: "# note". */
  text(): string;
  setText(text: string): TFComment;
  delete(): boolean;
}

/** An ordered list of items — order is source order, which is what keeps
 *  a comment next to the thing it describes. */
export interface TFBody {
  blocks(): TFBlock[];
  attributes(): TFAttribute[];
  comments(): TFComment[];
  attribute(name: string): TFAttribute | null;
  /** Set an attribute to a value, appending it when absent. The value is
   *  encoded as HCL: a string becomes a quoted literal, a number or
   *  boolean its own, an array a list, an object an object, nested as
   *  deep as it goes. A string is a string — for a reference or a
   *  function call use setAttributeRaw, or pass "${var.region}", which
   *  is unwrapped back into the expression it denotes. */
  setAttribute(name: string, value: unknown): TFAttribute;
  /** Set an attribute to raw source text, for an expression rather than
   *  a value. Written as given. */
  setAttributeRaw(name: string, expr: string): TFAttribute;
  removeAttribute(name: string): boolean;
  appendComment(text: string): TFComment;
  /** Add a block whose shape belongs to its parent rather than to the
   *  file — lifecycle, connection, validation, provisioner. */
  addBlock(type: string, ...labels: string[]): TFGeneric;
  /** Find one of those, or null. Top-level blocks have typed accessors
   *  on TFFile instead. */
  block(type: string, ...labels: string[]): TFBlock | null;
  remove(item: TFItem | null): boolean;
}

/** What every block shares. The interfaces below add only the labels
 *  their own block has: Terraform gives them no uniform shape. */
export interface TFBlock {
  blockType(): string;
  labels(): string[];
  /** The block's contents. The methods below reach straight through it,
   *  so this is for holding onto a body rather than for every call. */
  body(): TFBody;
  delete(): boolean;

  attribute(name: string): TFAttribute | null;
  attributes(): TFAttribute[];
  setAttribute(name: string, value: unknown): TFAttribute;
  setAttributeRaw(name: string, expr: string): TFAttribute;
  removeAttribute(name: string): boolean;
  blocks(): TFBlock[];
  block(type: string, ...labels: string[]): TFBlock | null;
  addBlock(type: string, ...labels: string[]): TFGeneric;
  comments(): TFComment[];
  appendComment(text: string): TFComment;
  items(): TFItem[];
  remove(item: TFItem | null): boolean;
}

export interface TFResource extends TFBlock {
  resourceType(): string;
  setResourceType(type: string): TFResource;
  name(): string;
  setName(name: string): TFResource;
}
export interface TFDataSource extends TFBlock {
  dataType(): string;
  setDataType(type: string): TFDataSource;
  name(): string;
  setName(name: string): TFDataSource;
}
export interface TFEphemeral extends TFBlock {
  ephemeralType(): string;
  setEphemeralType(type: string): TFEphemeral;
  name(): string;
  setName(name: string): TFEphemeral;
}
export interface TFAction extends TFBlock {
  actionType(): string;
  setActionType(type: string): TFAction;
  name(): string;
  setName(name: string): TFAction;
}
/** provider takes one label — the provider's local name. Several blocks
 *  may share it, told apart by an alias attribute. */
export interface TFProvider extends TFBlock {
  name(): string;
  setName(name: string): TFProvider;
  alias(): string;
}
export interface TFNamedBlock extends TFBlock {
  name(): string;
  setName(name: string): TFNamedBlock;
}
export interface TFModule extends TFNamedBlock {
  /** The module's source, the one attribute every module must have. */
  source(): string;
}
/** A block with no labels: terraform, locals, moved, removed, import. */
export interface TFUnlabelledBlock extends TFBlock {}
/** A block this layer does not model — a nested one, or a type Terraform
 *  adds later. Readable and editable, without named label accessors. */
export interface TFGeneric extends TFBlock {
  setLabels(labels: string[]): TFGeneric;
}

/** A parsed Terraform file. Each accessor takes exactly the labels its
 *  block has, and returns null when there is no such block. */
export interface TFFile {
  /** The top-level body. The methods below reach through it. */
  body(): TFBody;
  blocks(): TFBlock[];
  /** Top-level comments. One inside a block belongs to that block. */
  comments(): TFComment[];
  items(): TFItem[];
  remove(item: TFItem | null): boolean;

  resource(type: string, name: string): TFResource | null;
  resources(type?: string): TFResource[];
  addResource(type: string, name: string): TFResource;

  dataSource(type: string, name: string): TFDataSource | null;
  dataSources(type?: string): TFDataSource[];
  addDataSource(type: string, name: string): TFDataSource;

  ephemeral(type: string, name: string): TFEphemeral | null;
  addEphemeral(type: string, name: string): TFEphemeral;

  action(type: string, name: string): TFAction | null;
  addAction(type: string, name: string): TFAction;

  provider(name: string): TFProvider | null;
  providers(): TFProvider[];
  addProvider(name: string): TFProvider;

  variable(name: string): TFNamedBlock | null;
  variables(): TFNamedBlock[];
  addVariable(name: string): TFNamedBlock;

  output(name: string): TFNamedBlock | null;
  outputs(): TFNamedBlock[];
  addOutput(name: string): TFNamedBlock;

  module(name: string): TFModule | null;
  modules(): TFModule[];
  addModule(name: string): TFModule;

  check(name: string): TFNamedBlock | null;
  checks(): TFNamedBlock[];
  addCheck(name: string): TFNamedBlock;

  terraform(): TFUnlabelledBlock | null;
  addTerraform(): TFUnlabelledBlock;
  locals(): TFUnlabelledBlock[];
  addLocals(): TFUnlabelledBlock;
  moved(): TFUnlabelledBlock[];
  addMoved(): TFUnlabelledBlock;
  removed(): TFUnlabelledBlock[];
  addRemoved(): TFUnlabelledBlock;
  imports(): TFUnlabelledBlock[];
  addImport(): TFUnlabelledBlock;

  /** Print the file. Every node not edited comes back as its original
   *  bytes, so comments and formatting survive. */
  toString(): string;
}

export interface TerraformCodec {
  /** Parse HCL into a tree: typed block lookups, editable in place, and
   *  printing back with every node you did not touch coming out as its
   *  original bytes. Comments and formatting survive. Throws on
   *  malformed HCL. */
  parse(s: string): TFFile;
  /** Serialize back to HCL. A TFFile prints from the original bytes; a
   *  plain object in Terraform.tf.json shape has none to print from and
   *  is generated canonically. */
  stringify(value: TFFile | unknown): string;
  /** Read HCL as plain data in the .tf.json shape Terraform defines,
   *  when a tree is more than the job needs. Expressions arrive as
   *  "${var.region}" strings and comments are not represented, so this
   *  is for reading rather than for editing a file in place. */
  toObject(s: string): unknown;
}

export interface Std {
  /** Read the entire file as a string, or null on failure. The path is
   *  resolved relative to the veil project root — the first ancestor
   *  directory (walking up from where `veil` was invoked) that
   *  contains a veil.json. */
  loadFile(path: string): string | null;
  /** Read the value of an environment variable, or undefined if unset. */
  getenv(name: string): string | undefined;
  /** YAML codec — parse and stringify without an npm dependency. Backed
   *  by gopkg.in/yaml.v3 on the host side. JSON is available via the
   *  native JSON global. */
  yaml: YamlCodec;
  /** Terraform/HCL codec, for reading and writing .tf as data rather
   *  than as text. Backed by hashicorp/hcl on the host side. */
  terraform: TerraformCodec;
}

/** File metadata returned by os.stat / os.lstat. All values are numbers. */
export interface Stats {
  dev: number;
  ino: number;
  mode: number;
  nlink: number;
  uid: number;
  gid: number;
  rdev: number;
  size: number;
  blocks: number;
  atime: number;
  mtime: number;
  ctime: number;
}

export interface Os {
  /** List directory entries. Returns [names, error] — error is 0 on success. */
  readdir(path: string): [string[], number];
  /** File metadata, following symlinks. Returns [stats, error]. */
  stat(path: string): [Stats, number];
  /** File metadata, *not* following symlinks. Returns [stats, error]. */
  lstat(path: string): [Stats, number];
  /** Resolve to a canonical absolute path. Returns [path, error]. */
  realpath(path: string): [string, number];
  /** Read a symbolic link's target. Returns [target, error]. */
  readlink(path: string): [string, number];
  /** Process working directory — returns [cwd, error]. */
  getcwd(): [string, number];
  /** Platform identifier (e.g. "linux", "darwin"). */
  platform: string;
}

export interface FetchInit {
  method?: string;
  headers?: Record<string, string>;
  body?: string;
}

export interface FetchHeaders {
  get(name: string): string | null;
  has(name: string): boolean;
  forEach(fn: (value: string, key: string) => void): void;
}

export interface FetchResponse {
  status: number;
  statusText: string;
  ok: boolean;
  url: string;
  headers: FetchHeaders;
  text(): Promise<string>;
  json(): Promise<unknown>;
}

/** Web Fetch-style client. Strings only for body; no streaming, no
 *  AbortController. See SPEC.md for the full list of intentional gaps. */
export type Fetch = (
  input: string | (FetchInit & { url: string }),
  init?: FetchInit,
) => Promise<FetchResponse>;

export interface File<T = string> {
  /** Current contents. For a schema-declared source, validated against
   *  the schema on every call — a violation throws. The typed accessor
   *  hands back the parsed object; the plain File / escape hatch hands
   *  back the raw string (still validated underneath). */
  getContent(): T;
  /** Overwrite the contents. Same split and validation as getContent. */
  setContent(content: T): void;
  /** Current destination path, relative to the render output directory. */
  getPath(): string;
  /** Override the destination path. Identity (the FS key) is unchanged, so
   *  downstream hooks still find this file via the same typed accessor.
   *  Routing a file somewhere is a statement that it should be written, so
   *  this also marks it rendered. */
  setOutputPath(path: string): void;
  /** True when this file becomes rendered output. False for an asset the
   *  kind ships purely for hooks to read, and for anything deleted. */
  isRendered(): boolean;
  /** Turn output on or off for this entry. The entry stays in the FS
   *  either way, so downstream hooks still find it via the same typed
   *  accessor. */
  setRendered(render: boolean): void;
  /** The inverse of isRendered, and the same underlying state: a deleted
   *  file and an asset are both entries nothing writes. So this is also
   *  true for an asset the kind never meant to render. */
  isDeleted(): boolean;
  /** Tombstone (true) or restore (false) this entry — setRendered read
   *  the other way round. Identity is preserved either way. */
  setDeleted(deleted: boolean): void;
}

export interface FS {
  /** Handle for the declared source "./sources/network.json". */
  getSourcesNetworkJson(): File<Network>;

  /** Look up a file handle by its path. Returns undefined if absent.
   *  Always File<string> — still schema-enforced, just doesn't parse
   *  for you. */
  get(path: string): File | undefined;
  /** Every file handle currently present (including tombstoned ones —
   *  filter via `file.isDeleted()` if you only want live files). */
  getAll(): File[];
  /** Create a new file at the given path. Errors if a file with that path already exists. */
  add(path: string, content: string): File;
  /** Tombstone the file at the given path (soft delete — downstream hooks still see it). */
  delete(path: string): void;
  /** All paths currently present. */
  keys(): string[];
}

export interface Network {
  cidr: string;
  region: string;
  zones: number;
}

/** No targets accept this kind as a consumer; `dependencies` may only be omitted or empty. */
export type Dependency = never;

export interface Override {
  /** Path of the source file in the kind being replaced. */
  source: string;
  /** Local path to the override file. */
  path: string;
}

export interface Metadata {
  /** Name of the kind this resource instantiates. */
  kind: string;
  /** Name of this resource. */
  name: string;
  /** Source files ejected for local override. */
  overrides?: Override[];
}

export interface Resource<Spec, Deps = never> {
  /** Standard metadata common to every resource. */
  metadata: Metadata;
  /** Resource-specific data, validated against the kind's schema and
   *  with any matching overlays already merged in. */
  spec: Spec;
  /** Declared dependencies on other resources. The Deps type
   *  parameter narrows the per-entry shape to the targets this kind
   *  is actually allowed to depend on. */
  dependencies?: Deps[];
}

export interface RenderHookContext {
  /** The resource being rendered — full metadata + merged spec. */
  resource: Resource<VpcSpec, Dependency>;
  /** Path of the resource file being rendered, relative to the veil
   *  project root. Useful for hooks that need to locate sibling files
   *  (e.g. a service's package.json) by deriving paths from where the
   *  resource lives on disk. */
  path: string;
  /** Resolved input variables (from --var, env, or defaults). */
  vars: RegistryVariables;
  /** Absolute path of the veil project root — the directory housing
   *  veil.json. Provided for display / logging; std and os already
   *  resolve paths relative to this root. */
  root: string;
  /** Read-only file / env access. Paths resolve relative to the project
   *  root; use plain relative strings like "data.txt". */
  std: Std;
  /** Read-only filesystem inspection — list directories, stat, resolve
   *  symlinks. Paths resolve relative to the project root. */
  os: Os;
  /** Web Fetch-style HTTP client. Honors the host's allowlist, timeout,
   *  and response-size cap. */
  fetch: Fetch;
  /** Environment variables granted to this hook via its kind.json
   *  access.env declaration. Frozen — only the keys declared (and
   *  present on the host at render time) appear here. */
  env: Readonly<Record<string, string>>;
}

export interface RenderHook {
  /**
   * Called during `veil render` to transform the filesystem state for one
   * resource. Receives a RenderHookContext (resource, vars, root, std, os,
   * fetch) and the current FS; return the (optionally mutated) FS to flow
   * it into the next hook in the pipeline.
   *
   * Read declared sources via typed accessors (e.g. `fs.getSourcesDeploymentYaml()`)
   * — for a schema-declared source, getContent()/setContent() traffic in
   * the parsed, schema-validated object directly rather than a raw string.
   * Modify a file with `setContent`, `setOutputPath`, or `setDeleted`. Create
   * new files with `fs.add(path, content)`. Soft-delete with `fs.delete(path)` —
   * tombstoned files persist so downstream hooks can observe them via
   * `file.isDeleted()`, and are skipped at final write. A kind can also
   * ship assets: files declared without `render`, readable here and never
   * written, which `setRendered(true)` promotes to output.
   *
   * Returning nothing passes the FS through unchanged. `throw new Error(...)`
   * to abort the render for this resource. May be `async` — the host awaits
   * the returned Promise transparently before handing the result off.
   */
  render(ctx: RenderHookContext, fs: FS): FS | void | Promise<FS | void>;
}

export interface ValidationIssue {
  /** Required. Human-readable description of what failed. Surfaced
   *  verbatim in the aggregated render report. */
  message: string;
  /** Optional FS path or JSON-pointer-style locator that pinpoints where
   *  the issue lives (e.g. `sources/app.yaml` or `spec.replicas`). */
  path?: string;
  /** Optional severity tag. `'error'` (the default) fails the render;
   *  `'warning'` is reported but does not fail. */
  severity?: 'error' | 'warning';
}

/** A validate hook may return an issue list, a single issue, a single
 *  message string, or nothing. Throwing is treated as a single
 *  error-severity issue. */
export type ValidationResult =
  | void
  | string
  | ValidationIssue
  | Array<string | ValidationIssue>;

export interface ValidateHook {
  /**
   * Called during `veil render` after every other lifecycle point has
   * finished (kind render hooks, dependents, and any resource-level
   * hooks). Receives the same RenderHookContext + FS as a render hook
   * but is purely observational: any mutations the hook makes to the
   * FS or ctx are discarded by the runner. Returning a list of
   * issues — or throwing — fails the render with an aggregated
   * report. Every validate hook on the kind runs regardless of
   * failures so authors see every issue at once. May be `async`.
   */
  validate(ctx: RenderHookContext, fs: FS): ValidationResult | Promise<ValidationResult>;
}

// ---- Dependent hook types ----------------------------------------------
// One block per consumer kind that may declare a dependency on this
// kind. Each block replicates the consumer's spec / FS shape so the
// per-consumer hook receives concretely-typed `consumer` and `fs`.

/** A bundle of shared infrastructure a team adopts as one unit. Its dependencies are forwarded, so a service that depends on a platform inherits the platform's database and cache. */
export interface PlatformSpec {
  owner: string;
  tier: string;
}

export interface PlatformFS {
  /** Handle for the declared source "./sources/platform.json". */
  getSourcesPlatformJson(): File<PlatformPlatform>;

  /** Look up a file handle by its path. Returns undefined if absent.
   *  Always File<string> — still schema-enforced, just doesn't parse
   *  for you. */
  get(path: string): File | undefined;
  /** Every file handle currently present (including tombstoned ones —
   *  filter via `file.isDeleted()` if you only want live files). */
  getAll(): File[];
  /** Create a new file at the given path. Errors if a file with that path already exists. */
  add(path: string, content: string): File;
  /** Tombstone the file at the given path (soft delete — downstream hooks still see it). */
  delete(path: string): void;
  /** All paths currently present. */
  keys(): string[];
}

export interface PlatformPlatform {
  owner: string;
  provides: string[];
  tier: string;
}

/** Nothing is required to be placed in a VPC. */
export interface PlatformParams {
  note?: string;
}

export interface PlatformDependentHookContext {
  /** This kind's resolved resource. */
  self: Resource<VpcSpec, Dependency>;
  /** This kind's own files — the same FS its own hooks see,
   *  typed accessors included. Read from it to hand the consumer
   *  something this kind ships: `fs.add(path, ctx.selfFS.get(...)
   *  .getContent())`. Nothing is read back, so changes here do not
   *  affect this resource's own render. */
  selfFS: FS;
  /** The consumer resource that declared a dependency on us. */
  consumer: Resource<PlatformSpec>;
  /** Path of the consumer resource file being rendered, relative
   *  to the veil project root. */
  path: string;
  /** Params the consumer supplied for this dependency. */
  params: PlatformParams;
  vars: RegistryVariables;
  root: string;
  std: Std;
  os: Os;
  fetch: Fetch;
}

export interface PlatformDependentHook {
  /** Runs after the consumer's render hooks complete. Mutates the
   *  consumer's bundle to wire it up against this resource. */
  render(ctx: PlatformDependentHookContext, fs: PlatformFS): PlatformFS | void | Promise<PlatformFS | void>;
}

/** A managed Postgres instance. */
export interface PostgresSpec {
  multiAz: boolean;
  size: "small" | "medium" | "large";
  storageGb: number;
}

export interface PostgresFS {
  /** Handle for the declared source "./files/iam-policy.tf". */
  getFilesIamPolicyTf(): File;
  /** Handle for the declared source "./sources/database.json". */
  getSourcesDatabaseJson(): File<PostgresDatabase>;

  /** Look up a file handle by its path. Returns undefined if absent.
   *  Always File<string> — still schema-enforced, just doesn't parse
   *  for you. */
  get(path: string): File | undefined;
  /** Every file handle currently present (including tombstoned ones —
   *  filter via `file.isDeleted()` if you only want live files). */
  getAll(): File[];
  /** Create a new file at the given path. Errors if a file with that path already exists. */
  add(path: string, content: string): File;
  /** Tombstone the file at the given path (soft delete — downstream hooks still see it). */
  delete(path: string): void;
  /** All paths currently present. */
  keys(): string[];
}

export interface PostgresDatabase {
  engine: string;
  instanceClass: string;
  multiAz?: boolean;
  storageGb: number;
}

/** Nothing is required to be placed in a VPC. */
export interface PostgresParams {
  note?: string;
}

export interface PostgresDependentHookContext {
  /** This kind's resolved resource. */
  self: Resource<VpcSpec, Dependency>;
  /** This kind's own files — the same FS its own hooks see,
   *  typed accessors included. Read from it to hand the consumer
   *  something this kind ships: `fs.add(path, ctx.selfFS.get(...)
   *  .getContent())`. Nothing is read back, so changes here do not
   *  affect this resource's own render. */
  selfFS: FS;
  /** The consumer resource that declared a dependency on us. */
  consumer: Resource<PostgresSpec>;
  /** Path of the consumer resource file being rendered, relative
   *  to the veil project root. */
  path: string;
  /** Params the consumer supplied for this dependency. */
  params: PostgresParams;
  vars: RegistryVariables;
  root: string;
  std: Std;
  os: Os;
  fetch: Fetch;
}

export interface PostgresDependentHook {
  /** Runs after the consumer's render hooks complete. Mutates the
   *  consumer's bundle to wire it up against this resource. */
  render(ctx: PostgresDependentHookContext, fs: PostgresFS): PostgresFS | void | Promise<PostgresFS | void>;
}

/** A managed Redis cache. */
export interface RedisSpec {
  evictionPolicy: string;
  size: "small" | "large";
}

export interface RedisFS {
  /** Handle for the declared source "./sources/cache.yaml". */
  getSourcesCacheYaml(): File<RedisCache>;

  /** Look up a file handle by its path. Returns undefined if absent.
   *  Always File<string> — still schema-enforced, just doesn't parse
   *  for you. */
  get(path: string): File | undefined;
  /** Every file handle currently present (including tombstoned ones —
   *  filter via `file.isDeleted()` if you only want live files). */
  getAll(): File[];
  /** Create a new file at the given path. Errors if a file with that path already exists. */
  add(path: string, content: string): File;
  /** Tombstone the file at the given path (soft delete — downstream hooks still see it). */
  delete(path: string): void;
  /** All paths currently present. */
  keys(): string[];
}

export interface RedisCache {
  engine: string;
  evictionPolicy: string;
  nodes: number;
}

/** Nothing is required to be placed in a VPC. */
export interface RedisParams {
  note?: string;
}

export interface RedisDependentHookContext {
  /** This kind's resolved resource. */
  self: Resource<VpcSpec, Dependency>;
  /** This kind's own files — the same FS its own hooks see,
   *  typed accessors included. Read from it to hand the consumer
   *  something this kind ships: `fs.add(path, ctx.selfFS.get(...)
   *  .getContent())`. Nothing is read back, so changes here do not
   *  affect this resource's own render. */
  selfFS: FS;
  /** The consumer resource that declared a dependency on us. */
  consumer: Resource<RedisSpec>;
  /** Path of the consumer resource file being rendered, relative
   *  to the veil project root. */
  path: string;
  /** Params the consumer supplied for this dependency. */
  params: RedisParams;
  vars: RegistryVariables;
  root: string;
  std: Std;
  os: Os;
  fetch: Fetch;
}

export interface RedisDependentHook {
  /** Runs after the consumer's render hooks complete. Mutates the
   *  consumer's bundle to wire it up against this resource. */
  render(ctx: RedisDependentHookContext, fs: RedisFS): RedisFS | void | Promise<RedisFS | void>;
}

/** An Acme application service. */
export interface ServiceSpec {
  /** Drop the generated manifest from the rendered output. */
  dropManifest?: boolean;
  image: string;
  port: number;
  public: boolean;
  /** Emit the kind's standard labels as a file alongside the deployment. */
  publishLabels?: boolean;
  replicas: number;
}

export interface ServiceFS {
  /** Handle for the declared source "./files/labels.json". */
  getFilesLabelsJson(): File;
  /** Handle for the declared source "./sources/deployment.yaml". */
  getSourcesDeploymentYaml(): File<ServiceDeployment>;
  /** Handle for the declared source "./sources/env". */
  getSourcesEnv(): File;

  /** Look up a file handle by its path. Returns undefined if absent.
   *  Always File<string> — still schema-enforced, just doesn't parse
   *  for you. */
  get(path: string): File | undefined;
  /** Every file handle currently present (including tombstoned ones —
   *  filter via `file.isDeleted()` if you only want live files). */
  getAll(): File[];
  /** Create a new file at the given path. Errors if a file with that path already exists. */
  add(path: string, content: string): File;
  /** Tombstone the file at the given path (soft delete — downstream hooks still see it). */
  delete(path: string): void;
  /** All paths currently present. */
  keys(): string[];
}

export interface ServiceDeployment {
  image: string;
  /** Standard labels, seeded from the kind's labels.json asset. */
  labels?: Record<string, string>;
  port: number;
  public?: boolean;
  region: string;
  replicas: number;
}

export interface ServiceParams {
  subnet: "public" | "private";
}

export interface ServiceDependentHookContext {
  /** This kind's resolved resource. */
  self: Resource<VpcSpec, Dependency>;
  /** This kind's own files — the same FS its own hooks see,
   *  typed accessors included. Read from it to hand the consumer
   *  something this kind ships: `fs.add(path, ctx.selfFS.get(...)
   *  .getContent())`. Nothing is read back, so changes here do not
   *  affect this resource's own render. */
  selfFS: FS;
  /** The consumer resource that declared a dependency on us. */
  consumer: Resource<ServiceSpec>;
  /** Path of the consumer resource file being rendered, relative
   *  to the veil project root. */
  path: string;
  /** Params the consumer supplied for this dependency. */
  params: ServiceParams;
  vars: RegistryVariables;
  root: string;
  std: Std;
  os: Os;
  fetch: Fetch;
}

export interface ServiceDependentHook {
  /** Runs after the consumer's render hooks complete. Mutates the
   *  consumer's bundle to wire it up against this resource. */
  render(ctx: ServiceDependentHookContext, fs: ServiceFS): ServiceFS | void | Promise<ServiceFS | void>;
}

