// deref-jsonschema reads the bundled JSON Schema files generated by
// buf and produces simplified, fully-dereferenced schemas with clean
// filenames (e.g. ResourceDef.schema.json).
package main

import (
	"fmt"
	"log"
	"os"
	"path/filepath"
	"strings"

	"github.com/goccy/go-json"
)

func main() {
	if len(os.Args) != 2 {
		log.Fatal("usage: deref-jsonschema <dir>")
	}
	dir := os.Args[1]

	entries, err := os.ReadDir(dir)
	if err != nil {
		log.Fatalf("reading dir: %v", err)
	}

	for _, e := range entries {
		if !strings.HasSuffix(e.Name(), ".schema.bundle.json") {
			continue
		}

		path := filepath.Join(dir, e.Name())
		data, err := os.ReadFile(path)
		if err != nil {
			log.Fatalf("reading %s: %v", path, err)
		}

		var bundle map[string]any
		if err := json.Unmarshal(data, &bundle); err != nil {
			log.Fatalf("parsing %s: %v", path, err)
		}

		defs, _ := bundle["$defs"].(map[string]any)
		resolved := deref(bundle, defs)

		resolvedMap, ok := resolved.(map[string]any)
		if !ok {
			log.Fatalf("expected map at top level of %s", path)
		}
		delete(resolvedMap, "$defs")
		delete(resolvedMap, "$id")
		stripNestedSchema(resolvedMap)
		simplifyEnums(resolvedMap)
		wrapRenderHookSchema(resolvedMap)

		outName := simplifyName(e.Name())
		if pointedAtByFiles[outName] {
			allowSchemaKey(resolvedMap)
		}

		out, err := json.MarshalIndent(resolvedMap, "", "  ")
		if err != nil {
			log.Fatalf("marshalling: %v", err)
		}

		outPath := filepath.Join(dir, outName)

		if err := os.WriteFile(outPath, out, 0644); err != nil {
			log.Fatalf("writing %s: %v", outPath, err)
		}
		fmt.Printf("%s -> %s\n", e.Name(), outName)
	}

	if err := narrowSourceEntries(dir); err != nil {
		log.Fatalf("narrowing source entries: %v", err)
	}

	// Clean up original bundle and non-bundle files.
	entries, _ = os.ReadDir(dir)
	for _, e := range entries {
		name := e.Name()
		if strings.Contains(name, ".") && strings.Count(name, ".") > 2 {
			os.Remove(filepath.Join(dir, name))
		}
	}
}

// pointedAtByFiles are the schemas something writes a "$schema" key
// against: the three hand-authored shapes (`veil init` writes veil.json,
// `veil new kind` writes kind.json, resources reference Resource) and the
// two build artifacts (`veil build` stamps the compiled kind.json and
// registry.json). Every generated object schema sets
// additionalProperties:false, so without declaring the key the pointer is
// the file's first validation error — including in files veil wrote
// itself.
var pointedAtByFiles = map[string]bool{
	"VeilConfigDefinition.schema.json": true,
	"KindDefinition.schema.json":       true,
	"Resource.schema.json":             true,
	"Kind.schema.json":                 true,
	"Registry.schema.json":             true,
}

// allowSchemaKey declares the "$schema" property on a schema that files
// point at, so a validator checks the file instead of rejecting the
// reference to itself. veil ignores the value.
func allowSchemaKey(root map[string]any) {
	props, ok := root["properties"].(map[string]any)
	if !ok {
		return
	}
	if _, exists := props["$schema"]; exists {
		return
	}
	props["$schema"] = map[string]any{
		"type":        "string",
		"description": "URI of the JSON Schema this file is written against. Ignored by veil.",
	}
}

// narrowSourceEntries retypes KindDefinition's `sources` items. The proto
// field is a repeated google.protobuf.Value — protojson cannot express
// "string or message" — so the generated schema types every entry as
// anything at all: no completion, and no typo caught, on one of the
// fields a kind.json edits most. The two shapes it actually accepts are a
// bare path string and a SourceDefinition object, so say that, the same
// way `hooks` is already handled.
func narrowSourceEntries(dir string) error {
	var srcDef map[string]any
	if err := readJSON(filepath.Join(dir, "SourceDefinition.schema.json"), &srcDef); err != nil {
		return err
	}
	kindPath := filepath.Join(dir, "KindDefinition.schema.json")
	var kindDef map[string]any
	if err := readJSON(kindPath, &kindDef); err != nil {
		return err
	}

	props, ok := kindDef["properties"].(map[string]any)
	if !ok {
		return fmt.Errorf("KindDefinition has no properties")
	}
	sources, ok := props["sources"].(map[string]any)
	if !ok {
		return fmt.Errorf("KindDefinition has no sources property")
	}

	objectAlt := make(map[string]any, len(srcDef))
	for k, v := range srcDef {
		if k == "$schema" || k == "$id" || k == "title" {
			continue
		}
		objectAlt[k] = v
	}

	stringAlt := map[string]any{
		"type":      "string",
		"minLength": float64(1),
	}
	if defProps, ok := srcDef["properties"].(map[string]any); ok {
		if path, ok := defProps["path"].(map[string]any); ok {
			if desc, ok := path["description"].(string); ok {
				stringAlt["description"] = desc
			}
		}
	}

	sources["items"] = map[string]any{"oneOf": []any{stringAlt, objectAlt}}

	out, err := json.MarshalIndent(kindDef, "", "  ")
	if err != nil {
		return err
	}
	return os.WriteFile(kindPath, out, 0644)
}

// readJSON unmarshals a JSON file into v.
func readJSON(path string, v any) error {
	data, err := os.ReadFile(path)
	if err != nil {
		return err
	}
	return json.Unmarshal(data, v)
}

// deref recursively resolves all $ref pointers in a JSON Schema node.
func deref(node any, defs map[string]any) any {
	switch v := node.(type) {
	case map[string]any:
		if ref, ok := v["$ref"].(string); ok {
			if resolved := resolveRef(ref, defs); resolved != nil {
				merged := deref(resolved, defs).(map[string]any)
				result := make(map[string]any)
				for k, val := range merged {
					result[k] = val
				}
				for k, val := range v {
					if k == "$ref" {
						continue
					}
					result[k] = deref(val, defs)
				}
				return result
			}
		}
		result := make(map[string]any)
		for k, val := range v {
			if k == "$defs" {
				continue
			}
			result[k] = deref(val, defs)
		}
		return result
	case []any:
		result := make([]any, len(v))
		for i, val := range v {
			result[i] = deref(val, defs)
		}
		return result
	default:
		return node
	}
}

func resolveRef(ref string, defs map[string]any) map[string]any {
	const prefix = "#/$defs/"
	if !strings.HasPrefix(ref, prefix) {
		return nil
	}
	key := strings.TrimPrefix(ref, prefix)
	if def, ok := defs[key]; ok {
		if m, ok := def.(map[string]any); ok {
			cp := make(map[string]any)
			for k, v := range m {
				cp[k] = v
			}
			return cp
		}
	}
	return nil
}

func stripNestedSchema(root map[string]any) {
	for k, v := range root {
		if k == "$schema" {
			continue
		}
		stripSchemaRecursive(v)
	}
}

func stripSchemaRecursive(node any) {
	switch v := node.(type) {
	case map[string]any:
		delete(v, "$schema")
		for _, val := range v {
			stripSchemaRecursive(val)
		}
	case []any:
		for _, val := range v {
			stripSchemaRecursive(val)
		}
	}
}

func simplifyEnums(node any) {
	switch v := node.(type) {
	case map[string]any:
		if anyOf, ok := v["anyOf"].([]any); ok {
			var stringValues []any
			hasInt := false
			hasEnum := false
			for _, alt := range anyOf {
				m, ok := alt.(map[string]any)
				if !ok {
					continue
				}
				if m["type"] == "integer" {
					hasInt = true
					continue
				}
				if m["type"] == "string" {
					if vals, ok := m["enum"].([]any); ok {
						hasEnum = true
						stringValues = append(stringValues, vals...)
					} else if pat, ok := m["pattern"].(string); ok {
						pat = strings.TrimPrefix(pat, "^")
						pat = strings.TrimSuffix(pat, "$")
						stringValues = append(stringValues, pat)
					}
				}
			}
			if hasInt && hasEnum && len(stringValues) > 0 {
				delete(v, "anyOf")
				delete(v, "default")
				v["type"] = "string"
				v["enum"] = stringValues
			}
		}
		for _, val := range v {
			simplifyEnums(val)
		}
	case []any:
		for _, val := range v {
			simplifyEnums(val)
		}
	}
}

// wrapRenderHookSchema rewrites every RenderHookDefinition object schema
// into a oneOf accepting either the original object shape or a bare string
// (shorthand for `{path: <string>}`). The kind.json loader normalizes the
// string form back into the object before protojson sees it; this transform
// keeps editors and external validators happy with both shapes.
func wrapRenderHookSchema(node any) {
	switch v := node.(type) {
	case map[string]any:
		if v["title"] == "Render Hook Definition" && v["type"] == "object" {
			schemaURI := v["$schema"]
			description := v["description"]

			stringAlt := map[string]any{
				"type":      "string",
				"minLength": float64(1),
			}
			if props, ok := v["properties"].(map[string]any); ok {
				if path, ok := props["path"].(map[string]any); ok {
					if desc, ok := path["description"].(string); ok {
						stringAlt["description"] = desc
					}
				}
			}

			objectAlt := make(map[string]any, len(v))
			for k, val := range v {
				if k == "title" || k == "description" || k == "$schema" {
					continue
				}
				objectAlt[k] = val
			}

			for k := range v {
				delete(v, k)
			}
			if schemaURI != nil {
				v["$schema"] = schemaURI
			}
			v["title"] = "Render Hook Definition"
			if description != nil {
				v["description"] = description
			}
			v["oneOf"] = []any{stringAlt, objectAlt}
			return
		}
		for _, val := range v {
			wrapRenderHookSchema(val)
		}
	case []any:
		for _, val := range v {
			wrapRenderHookSchema(val)
		}
	}
}

func simplifyName(name string) string {
	name = strings.Replace(name, ".bundle", "", 1)
	parts := strings.Split(name, ".")
	for i, p := range parts {
		if len(p) > 0 && p[0] >= 'A' && p[0] <= 'Z' {
			return strings.Join(parts[i:], ".")
		}
	}
	return name
}
