package commands

import (
	"context"
	"errors"
	"fmt"
	"io/fs"
	"log/slog"
	"os"
	"path"
	"path/filepath"
	"strings"

	"github.com/goccy/go-json"
	"github.com/urfave/cli/v3"

	veilv1 "github.com/vercel/veil/api/go/veil/v1"
	"github.com/vercel/veil/pkg/build"
	"github.com/vercel/veil/pkg/bundle"
	"github.com/vercel/veil/pkg/config"
	"github.com/vercel/veil/pkg/embeds"
	"github.com/vercel/veil/pkg/interact"
	"github.com/vercel/veil/pkg/protoencode"
	"github.com/vercel/veil/pkg/resource"
	"github.com/vercel/veil/pkg/tsc"
	"github.com/vercel/veil/pkg/vfs"
)

// Build returns the "build" command — compiles every kind into
// <out>/<name>/kind.json (sources + minified hooks) and emits the composite
// resource JSON schema at <out>/<name>/kind.schema.json, plus a top-level
// <out>/registry.json indexing them.
func Build() *cli.Command {
	configDefault := "veil.json"
	outDefault := filepath.Join(config.PublicDir, "r")
	if cwd, err := os.Getwd(); err == nil {
		if reg, err := config.Discover(cwd); err == nil {
			configDefault = reg.ConfigPath
			outDefault = filepath.Join(reg.Root, config.PublicDir, "r")
		}
	}

	return &cli.Command{
		Name:      "build",
		Usage:     "Compile every kind into a self-contained JSON document and its composite schema",
		UsageText: "veil build [--config <path>] [--out <dir>] [--no-typecheck]",
		Flags: []cli.Flag{
			&cli.StringFlag{
				Name:  "config",
				Usage: "Path to veil.json",
				Value: configDefault,
			},
			&cli.StringFlag{
				Name:  "out",
				Usage: "Output directory for compiled kinds and schemas",
				Value: outDefault,
			},
			&cli.BoolFlag{
				Name:  "no-typecheck",
				Usage: "Skip running tsc --noEmit on each kind's hooks",
			},
			&cli.BoolFlag{
				Name:  "schemas-only",
				Usage: "Write only each kind's kind.schema.json — skip the compiled kind.json bodies and the registry.json index. The schemas are safe to commit (for $schema editor validation); the compiled registry stays in-memory (veil render --build).",
			},
		},
		Action: withResult(runBuild),
	}
}

// builtKind describes one compiled kind in a buildResponse.
type builtKind struct {
	Name     string `json:"name"`
	Compiled string `json:"compiled"`
	Schema   string `json:"schema"`
	Types    string `json:"types"`
}

// buildResponse is the JSON payload for `veil build`.
type buildResponse struct {
	Kinds     []builtKind           `json:"kinds"`
	Resources []regeneratedResource `json:"resources,omitempty"`
	Registry  string                `json:"registry"`
}

// regeneratedResource describes one resource whose render-hook
// veil-types.ts was regenerated by `veil build` (see regenResourceTypes).
type regeneratedResource struct {
	Path  string `json:"path"`
	Kind  string `json:"kind"`
	Types string `json:"types"`
}

func runBuild(ctx context.Context, c *cli.Command) (*buildResponse, error) {
	p := interact.Default()

	reg, err := config.Load(c.String("config"))
	if err != nil {
		return nil, err
	}
	slog.Debug("loaded registry", "root", reg.Root, "kinds", len(reg.Kinds))

	configPath := reg.ConfigPath
	if cwd, err := os.Getwd(); err == nil {
		if rel, err := filepath.Rel(cwd, configPath); err == nil && !strings.HasPrefix(rel, "..") {
			configPath = rel
		}
	}
	p.Infof("Using %s", configPath)

	schemasOnly := c.Bool("schemas-only")
	return runBuildPipeline(ctx, reg, vfs.NewDir(c.String("out")), buildPipelineOpts{
		typecheck:     !schemasOnly && !c.Bool("no-typecheck"),
		writeTypes:    !schemasOnly,
		resourceTypes: !schemasOnly,
		schemasOnly:   schemasOnly,
	})
}

// buildPipelineOpts tunes runBuildPipeline.
type buildPipelineOpts struct {
	// typecheck runs tsc/tsgo over each kind's hooks when a compiler is
	// on PATH.
	typecheck bool
	// writeTypes regenerates veil-types.ts in each kind's hooks/src (a
	// source-tree artifact). Off for in-memory builds (e.g. render
	// --build), which must not touch the working tree.
	writeTypes bool
	// resourceTypes additionally regenerates the veil-types.ts beside
	// every discovered resource's render hooks, keyed to each resource's
	// kind, so resource-hook authors get the same up-to-date TS surface
	// as kind hooks. Only `veil build` sets it; `veil new` (which targets
	// a single kind) and in-memory render builds leave it off.
	resourceTypes bool
	// schemasOnly writes only each kind's kind.schema.json — no compiled
	// kind.json bodies and no registry.json. `veil build --schemas-only`
	// uses it to refresh the committed schema files without emitting the
	// heavy registry, which render builds in memory.
	schemasOnly bool
}

// runBuildPipeline compiles every kind into <name>/kind.json, writes its
// composite JSON schema to <name>/kind.schema.json, and an index at
// registry.json — all written through dst (an on-disk dir or an in-memory
// FS) at registry-relative paths. Called by `veil build`, `veil new
// kind|hook` (so scaffolding leaves a buildable state), and `veil render
// --build` (into an in-memory FS the registry then reads via FSStore).
func runBuildPipeline(ctx context.Context, reg *config.Registry, dst vfs.FS, opts buildPipelineOpts) (*buildResponse, error) {
	p := interact.Default()
	resp := &buildResponse{Kinds: []builtKind{}}

	var metadataSchema map[string]any
	if err := json.Unmarshal(embeds.MetadataSchema, &metadataSchema); err != nil {
		return nil, fmt.Errorf("parsing embedded metadata schema: %w", err)
	}
	delete(metadataSchema, "$schema")
	delete(metadataSchema, "title")

	// Bake the project's declared variable names into each overlay's
	// `if` properties so a typo in a variable reference fails schema
	// validation rather than silently never matching.
	build.ShapeOverlayIf(metadataSchema, reg.Variables)

	// Bundle entrypoints are relative to the project root (= reg.Root).
	fsys := os.DirFS(reg.Root)

	// display turns a registry-relative output path into the string shown
	// to the user. On disk that's the real (cwd-relative) location; for an
	// in-memory build it's just the registry-relative path.
	display := func(rel string) string { return rel }
	if dir, ok := dst.(*vfs.Dir); ok {
		display = func(rel string) string { return cwdRel(filepath.Join(dir.Root(), filepath.FromSlash(rel))) }
	}

	var checker tsc.Checker
	if opts.typecheck {
		checker = tsc.Find()
		if checker == nil {
			p.Warn("no TypeScript compiler on PATH — skipping type check. Install `tsgo` or `tsc` to enable it.")
		}
	}

	index := &veilv1.Registry{Kinds: make(map[string]*veilv1.RegistryEntry, len(reg.Kinds))}

	graph, err := build.BuildGraph(reg.Kinds)
	if err != nil {
		return nil, fmt.Errorf("building kind graph: %w", err)
	}

	// Resolve the shared types package (generators.types) once. nil when no
	// kind opts in — every kind then falls back to its inline veil-types.ts.
	// Skipped for in-memory builds, which must not touch the source tree.
	var tp *typesPackage
	if opts.writeTypes {
		tp, err = resolveTypesPackage(reg)
		if err != nil {
			return nil, fmt.Errorf("resolving types package: %w", err)
		}
		if tp != nil {
			if err := tp.writeShared(reg); err != nil {
				return nil, fmt.Errorf("writing types package: %w", err)
			}
		}
	}

	var errs []error
	var builtImportKinds []string // import kinds whose module was written, for the manifest
	for _, k := range reg.Kinds {
		if err := validateKind(k); err != nil {
			errs = append(errs, fmt.Errorf("%s: %w", k.Name, err))
			continue
		}

		schemaRel := path.Join(k.Name, "kind.schema.json")
		schemaBytes, err := build.ResourceSchemaBytes(k, metadataSchema, graph)
		if err != nil {
			errs = append(errs, fmt.Errorf("%s: generating schema: %w", k.Name, err))
			continue
		}
		if err := dst.WriteFile(schemaRel, schemaBytes); err != nil {
			errs = append(errs, fmt.Errorf("%s: %w", k.Name, err))
			continue
		}

		// --schemas-only stops at the schema: no hook compile, no
		// kind.json, no registry index entry.
		if opts.schemasOnly {
			resp.Kinds = append(resp.Kinds, builtKind{Name: k.Name, Schema: display(schemaRel)})
			p.Successf("Built schema %s", k.Name)
			p.KeyValue("schema", display(schemaRel))
			continue
		}

		// Regenerate types before bundling so hook imports resolve against
		// the freshest schema. Skipped for in-memory builds, which must
		// not write into the source tree.
		typesPath := ""
		if opts.writeTypes {
			if tp.has(k.Name) {
				// Package mode: write the kind's module into the shared types
				// package and wire its hooks' package.json to depend on it,
				// instead of emitting a per-hook veil-types.ts.
				file, err := tp.writeKindModule(k, reg, graph)
				if err != nil {
					errs = append(errs, fmt.Errorf("%s: writing types: %w", k.Name, err))
					continue
				}
				// Drop any stale inline veil-types.ts left from before the
				// kind opted into the shared package.
				_ = os.Remove(filepath.Join(k.Dir, "hooks", "src", "veil-types.ts"))
				// Floor the dependency search at the kind dir — the hooks
				// package.json sits directly under it.
				if err := ensureTypesDep(filepath.Join(k.Dir, "hooks"), k.Dir, tp.name, k.Import.GetValue()); err != nil {
					errs = append(errs, fmt.Errorf("%s: wiring types dependency: %w", k.Name, err))
					continue
				}
				builtImportKinds = append(builtImportKinds, k.Name)
				typesPath = cwdRel(file)
			} else {
				if err := writeKindTypes(k, reg.Variables, graph); err != nil {
					errs = append(errs, fmt.Errorf("%s: writing types: %w", k.Name, err))
					continue
				}
				typesPath = cwdRel(filepath.Join(k.Dir, "hooks", "src", "veil-types.ts"))
			}
		}

		if checker != nil {
			if err := checker.Check(hookFiles(k)); err != nil {
				errs = append(errs, fmt.Errorf("%s: %w", k.Name, err))
				continue
			}
		}

		ck, err := compileKind(k, reg.Variables, reg.Root, fsys)
		if err != nil {
			errs = append(errs, fmt.Errorf("%s: %w", k.Name, err))
			continue
		}

		jsonRel := path.Join(k.Name, "kind.json")
		kindBytes, err := protoencode.MarshalFile(ck, embeds.KindSchemaURL)
		if err != nil {
			errs = append(errs, fmt.Errorf("%s: %w", k.Name, err))
			continue
		}
		if err := dst.WriteFile(jsonRel, kindBytes); err != nil {
			errs = append(errs, fmt.Errorf("%s: %w", k.Name, err))
			continue
		}

		index.Kinds[k.Name] = &veilv1.RegistryEntry{
			Name:   k.Name,
			Path:   "./" + jsonRel,
			Schema: "./" + schemaRel,
		}

		resp.Kinds = append(resp.Kinds, builtKind{
			Name:     k.Name,
			Compiled: display(jsonRel),
			Schema:   display(schemaRel),
			Types:    typesPath,
		})

		p.Successf("Built %s", k.Name)
		p.KeyValue("compiled", display(jsonRel))
		p.KeyValue("schema", display(schemaRel))
		if typesPath != "" {
			p.KeyValue("types", typesPath)
		}
	}

	if len(errs) > 0 {
		return nil, errors.Join(errs...)
	}

	// Write the types package manifest now that the set of successfully-built
	// kind modules is known, so its exports never reference a missing module.
	if tp != nil {
		if err := tp.writeManifest(builtImportKinds); err != nil {
			return nil, fmt.Errorf("writing types package manifest: %w", err)
		}
	}

	// --schemas-only emits no registry index — render builds it in memory.
	if opts.schemasOnly {
		return resp, nil
	}

	regBytes, err := protoencode.MarshalFile(index, embeds.RegistrySchemaURL)
	if err != nil {
		return nil, fmt.Errorf("writing registry: %w", err)
	}
	if err := dst.WriteFile("registry.json", regBytes); err != nil {
		return nil, fmt.Errorf("writing registry: %w", err)
	}
	resp.Registry = display("registry.json")
	p.Successf("Built registry")
	p.KeyValue("registry", display("registry.json"))

	// Regenerate the veil-types.ts next to every resource's render hooks
	// so resource-hook authors track the kind schema, just like kind
	// hooks do. Gated on resourceTypes (only a full `veil build`), so
	// `veil new` and in-memory render builds never touch the source tree.
	if opts.resourceTypes {
		resources, err := regenResourceTypes(ctx, reg, graph, fsys, tp)
		if err != nil {
			return nil, fmt.Errorf("regenerating resource hook types: %w", err)
		}
		resp.Resources = resources
	}
	return resp, nil
}

// cwdRel renders an absolute path relative to the working directory when
// that's a clean subpath, else returns it unchanged.
func cwdRel(abs string) string {
	cwd, err := os.Getwd()
	if err != nil {
		return abs
	}
	if rel, err := filepath.Rel(cwd, abs); err == nil && !strings.HasPrefix(rel, "..") {
		return rel
	}
	return abs
}

// compileKind reads a kind's sources, bundles+minifies each render hook,
// bundles each per-consumer dependent hook, and inlines per-consumer params
// schemas. `variables` is the merged variable declaration set (veil.json
// plus every kind's kind.json), copied verbatim so the compiled document
// is self-contained at render time.
func compileKind(k *config.Kind, variables map[string]*veilv1.Variable, projectRoot string, fsys fs.FS) (*veilv1.Kind, error) {
	sources := make(map[string]string, len(k.Sources))
	for _, src := range k.Sources {
		abs := src
		if !filepath.IsAbs(abs) {
			abs = filepath.Join(k.Dir, src)
		}
		data, err := os.ReadFile(abs)
		if err != nil {
			return nil, fmt.Errorf("reading source %s: %w", src, err)
		}
		key, err := filepath.Rel(k.Dir, abs)
		if err != nil {
			return nil, fmt.Errorf("resolving source key for %s: %w", src, err)
		}
		sources[filepath.ToSlash(key)] = string(data)
	}

	render, err := compileRenderHookDefs(k, projectRoot, fsys, k.RenderHooks())
	if err != nil {
		return nil, fmt.Errorf("render hooks: %w", err)
	}

	validate, err := compileRenderHookDefs(k, projectRoot, fsys, k.ValidateHooks())
	if err != nil {
		return nil, fmt.Errorf("validate hooks: %w", err)
	}

	postRender, err := compileRenderHookDefs(k, projectRoot, fsys, k.PostRenderHooks())
	if err != nil {
		return nil, fmt.Errorf("post_render hooks: %w", err)
	}

	dependents, err := compileDependents(k, projectRoot, fsys)
	if err != nil {
		return nil, err
	}

	return &veilv1.Kind{
		Name:    k.Name,
		Sources: sources,
		Hooks: &veilv1.Hooks{
			Render:     render,
			Dependents: dependents,
			Validate:   validate,
			PostRender: postRender,
		},
		Variables: variables,
	}, nil
}

// compileHookList bundles+minifies every hook path in paths, resolving
// each entrypoint relative to the kind's project root.
func compileHookList(k *config.Kind, projectRoot string, fsys fs.FS, paths []string) ([]*veilv1.Hook, error) {
	hooks := make([]*veilv1.Hook, 0, len(paths))
	for _, h := range paths {
		hk, err := compileHook(k, projectRoot, fsys, h)
		if err != nil {
			return nil, err
		}
		hooks = append(hooks, hk)
	}
	return hooks, nil
}

// compileRenderHookDefs compiles a slice of typed RenderHookDefinitions,
// bundling each path and stamping the entry's declared `access` onto
// the resulting compiled Hook so the runner can pre-flight required
// env vars at render time.
func compileRenderHookDefs(k *config.Kind, projectRoot string, fsys fs.FS, defs []*veilv1.RenderHookDefinition) ([]*veilv1.Hook, error) {
	hooks := make([]*veilv1.Hook, 0, len(defs))
	for _, d := range defs {
		hk, err := compileHook(k, projectRoot, fsys, d.GetPath())
		if err != nil {
			return nil, err
		}
		hk.Access = d.GetAccess()
		hooks = append(hooks, hk)
	}
	return hooks, nil
}

// compileHook bundles a single hook source file and returns it as a
// compiled Hook (without any access info — callers attach that).
func compileHook(k *config.Kind, projectRoot string, fsys fs.FS, h string) (*veilv1.Hook, error) {
	abs := h
	if !filepath.IsAbs(abs) {
		abs = filepath.Join(k.Dir, h)
	}
	entrypoint, err := filepath.Rel(projectRoot, abs)
	if err != nil {
		return nil, fmt.Errorf("resolving hook entrypoint for %s: %w", h, err)
	}
	code, err := bundle.Bundle(filepath.ToSlash(entrypoint), fsys, &bundle.Options{
		Minify:     true,
		GlobalName: "__veilMod",
	})
	if err != nil {
		return nil, fmt.Errorf("bundling %s: %w", h, err)
	}
	name, err := filepath.Rel(k.Dir, abs)
	if err != nil {
		return nil, fmt.Errorf("resolving hook name for %s: %w", h, err)
	}
	return &veilv1.Hook{
		Name:    filepath.ToSlash(name),
		Content: code,
	}, nil
}

// compileDependents bundles each per-consumer dependent entry's hooks and
// inlines the params JSON Schema referenced by params_path. Returns nil
// when the kind declares no dependents.
func compileDependents(k *config.Kind, projectRoot string, fsys fs.FS) ([]*veilv1.DependentHook, error) {
	dependents := k.GetHooks().GetDependents()
	if len(dependents) == 0 {
		return nil, nil
	}
	out := make([]*veilv1.DependentHook, 0, len(dependents))
	for _, d := range dependents {
		hooks, err := compileHookList(k, projectRoot, fsys, d.Paths)
		if err != nil {
			return nil, fmt.Errorf("dependents[%q]: %w", d.Kind, err)
		}
		paramsAbs := d.ParamsPath
		if !filepath.IsAbs(paramsAbs) {
			paramsAbs = filepath.Join(k.Dir, d.ParamsPath)
		}
		// Source may be authored in JSON or YAML; the compiled
		// kind.json always embeds JSON-encoded params so downstream
		// consumers (render, hook bundler) don't need a YAML parser
		// to interpret it.
		var probe map[string]any
		if err := protoencode.ReadFile(paramsAbs, &probe); err != nil {
			return nil, fmt.Errorf("dependents[%q]: reading params_path %s: %w", d.Kind, d.ParamsPath, err)
		}
		paramsJSON, err := json.Marshal(probe)
		if err != nil {
			return nil, fmt.Errorf("dependents[%q]: encoding params_path %s as JSON: %w", d.Kind, d.ParamsPath, err)
		}
		out = append(out, &veilv1.DependentHook{
			Kind:         d.Kind,
			Hooks:        hooks,
			ParamsSchema: string(paramsJSON),
		})
	}
	return out, nil
}

// writeKindTypes emits veil-types.ts alongside the hook .ts files in
// hooks/src/ so `import … from './veil-types'` resolves naturally and
// the package.json sitting one level up at hooks/ stays separate from
// the source code.
func writeKindTypes(k *config.Kind, variables map[string]*veilv1.Variable, graph *build.KindGraph) error {
	ts, err := build.VeilTypes(k, variables, graph, "")
	if err != nil {
		return err
	}
	dir := filepath.Join(k.Dir, "hooks", "src")
	if err := os.MkdirAll(dir, 0755); err != nil {
		return err
	}
	return os.WriteFile(filepath.Join(dir, "veil-types.ts"), []byte(ts), 0644)
}

// regenResourceTypes discovers every resource under the project's
// resource_discovery paths and, for each one that declares render hooks,
// regenerates the veil-types.ts beside those hooks — keyed to the
// resource's kind via the same build.VeilTypes generator the kind path
// uses. This keeps a resource hook's `import … from './veil-types'` in
// sync with the kind schema; `veil new hook` only writes it once, at
// scaffold time. Resources without render hooks have nothing to type and
// are skipped. Per-resource errors are collected so one bad resource
// doesn't mask the rest, then returned joined.
func regenResourceTypes(ctx context.Context, reg *config.Registry, graph *build.KindGraph, fsys fs.FS, tp *typesPackage) ([]regeneratedResource, error) {
	p := interact.Default()
	if reg.ResourceDiscovery == nil {
		return nil, nil
	}
	handles, err := resource.Discover(ctx, fsys, reg.ResourceDiscovery.GetPaths())
	if err != nil {
		return nil, fmt.Errorf("discovering resources: %w", err)
	}
	catalog, err := resource.NewCatalog(fsys, handles)
	if err != nil {
		return nil, fmt.Errorf("cataloguing resources: %w", err)
	}

	byName := make(map[string]*config.Kind, len(reg.Kinds))
	for _, k := range reg.Kinds {
		byName[k.Name] = k
	}

	var (
		out  []regeneratedResource
		errs []error
	)
	for _, h := range handles {
		r, err := catalog.LoadByPath(h.Path)
		if err != nil {
			errs = append(errs, fmt.Errorf("%s: %w", h.Path, err))
			continue
		}
		if len(r.RenderHooks) == 0 {
			continue
		}
		k := byName[h.Kind]
		if k == nil {
			errs = append(errs, fmt.Errorf("%s: references kind %q not registered in veil.json", h.Path, h.Kind))
			continue
		}
		// Package-mode kinds expose their types through the shared package
		// (written on the kind path); resource hooks import that package, so
		// here we only wire the dependency — no per-resource veil-types.ts to
		// generate. Inline kinds still get a freshly-generated veil-types.ts.
		var ts string
		if !tp.has(k.Name) {
			ts, err = build.VeilTypes(k, reg.Variables, graph, "")
			if err != nil {
				errs = append(errs, fmt.Errorf("%s: generating types: %w", h.Path, err))
				continue
			}
		}
		// A resource hook imports its types from the same directory (inline:
		// `./veil-types`) or the shared package (package mode), so act once
		// per distinct hook dir (normally just <resourceDir>/hooks).
		resourceDir := filepath.Dir(h.Path)
		resourceDirAbs := filepath.Join(reg.Root, resourceDir)
		written := make(map[string]struct{})
		for _, def := range r.RenderHooks {
			dir := filepath.Join(reg.Root, resourceDir, filepath.Dir(def.GetPath()))
			if _, dup := written[dir]; dup {
				continue
			}
			written[dir] = struct{}{}

			if tp.has(k.Name) {
				// Floor the search at the resource dir so the dependency never
				// lands in an unrelated ancestor manifest (a service's app
				// package.json or the monorepo root). With no package.json of
				// its own, warn and skip rather than polluting an ancestor.
				pkgPath := nearestPackageJSON(dir, resourceDirAbs)
				if pkgPath == "" {
					p.Warnf("skipping types dependency for %s: no package.json under %s", h.Name, cwdRel(resourceDirAbs))
					continue
				}
				if err := addDepToPackageJSON(pkgPath, tp.name, k.Import.GetValue()); err != nil {
					errs = append(errs, fmt.Errorf("%s: wiring types dependency: %w", h.Path, err))
					continue
				}
				// Drop any stale inline veil-types.ts beside the resource hook.
				_ = os.Remove(filepath.Join(dir, "veil-types.ts"))
				out = append(out, regeneratedResource{
					Path: cwdRel(filepath.Join(reg.Root, h.Path)),
					Kind: h.Kind,
				})
				p.Successf("Wired resource types dependency for %s", h.Name)
				continue
			}

			if err := os.MkdirAll(dir, 0755); err != nil {
				errs = append(errs, fmt.Errorf("%s: %w", h.Path, err))
				continue
			}
			typesPath := filepath.Join(dir, "veil-types.ts")
			if err := os.WriteFile(typesPath, []byte(ts), 0644); err != nil {
				errs = append(errs, fmt.Errorf("%s: %w", h.Path, err))
				continue
			}
			out = append(out, regeneratedResource{
				Path:  cwdRel(filepath.Join(reg.Root, h.Path)),
				Kind:  h.Kind,
				Types: cwdRel(typesPath),
			})
			p.Successf("Regenerated resource types for %s", h.Name)
			p.KeyValue("types", cwdRel(typesPath))
		}
	}
	if len(errs) > 0 {
		return out, errors.Join(errs...)
	}
	return out, nil
}

// hookFiles returns the absolute paths of every hook .ts file declared
// in a kind — render hooks plus dependent hooks. Used to scope tsc to
// exactly the files veil ships, so it never tries to type-check unrelated
// files in a surrounding monorepo.
func hookFiles(k *config.Kind) []string {
	abs := func(p string) string {
		if filepath.IsAbs(p) {
			return p
		}
		return filepath.Join(k.Dir, p)
	}
	var files []string
	for _, d := range k.RenderHooks() {
		files = append(files, abs(d.GetPath()))
	}
	for _, d := range k.ValidateHooks() {
		files = append(files, abs(d.GetPath()))
	}
	for _, d := range k.PostRenderHooks() {
		files = append(files, abs(d.GetPath()))
	}
	for _, d := range k.GetHooks().GetDependents() {
		for _, p := range d.GetPaths() {
			files = append(files, abs(p))
		}
	}
	return files
}

// validateKind checks that a kind's referenced files exist and that its
// spec schema parses as JSON.
func validateKind(k *config.Kind) error {
	var errs []error

	if k.Schema != "" {
		if _, err := build.LoadSpecSchema(k); err != nil {
			errs = append(errs, err)
		}
	}

	check := func(label string, paths []string) {
		for _, p := range paths {
			abs := p
			if !filepath.IsAbs(abs) {
				abs = filepath.Join(k.Dir, p)
			}
			if _, err := os.Stat(abs); err != nil {
				errs = append(errs, fmt.Errorf("%s %q: %w", label, p, err))
			}
		}
	}
	check("source", k.Sources)
	for _, d := range k.RenderHooks() {
		check("render hook", []string{d.GetPath()})
	}
	for _, d := range k.ValidateHooks() {
		check("validate hook", []string{d.GetPath()})
	}
	for _, d := range k.PostRenderHooks() {
		check("post_render hook", []string{d.GetPath()})
	}

	for _, d := range k.GetHooks().GetDependents() {
		check(fmt.Sprintf("dependent[%q] path", d.Kind), d.Paths)
		check(fmt.Sprintf("dependent[%q] params_path", d.Kind), []string{d.ParamsPath})
	}

	return errors.Join(errs...)
}
